server:
  context-path: /saw
  port: 8000
  
spring:
  sleuth:
    sampler:
      percentage: 0.1

metadata:
     url : http://client.sncrbda.dev.cloud.synchronoss.net/      
     context: /md
execution:
     url: http://client.sncrbda.dev.cloud.synchronoss.net/
     context: /exe
semantic:
     url: http://client.sncrbda.dev.cloud.synchronoss.net/
     context: /semantic

client:
   context:
       security: /saw-security-service     

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false  

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
       enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
      
      
  
