mail:
    from: helpdesk@synchronoss.com
    host: outgoing.sncrcorp.net
    password: ''
    port: 25
    protocol: smtp
    smtp:
        auth: false
        starttls:
            enable: false
    subject: 'Request for Reset Password '
    username: ''
server:
    address: 127.0.0.1 
    context-path: /saw-security-service
    port: 9000
    tomcat:
        compressableMimeTypes: application/json
        compression: 'on'
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        logValidationErrors: true
        max-active: 25
        password: ZGV2cGFzcw==
        testOnBorrow: true
        testOnConnect: true
        testOnReturn: true
        testWhileIdle: true
        url: jdbc:mariadb://10.49.0.169:3306/saw_dev
        username: dev_user
        validationQuery: SELECT 1
    sleuth:
        sampler:
         percentage: 1.0
        
ticket:
    validity:
        mins: 120
shell:
    auth:
       simple:
           user:
               name: saw
               password: saw
management:
     security:
       enabled: false
     shell:
       ssh:
         port: 2002
     
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false  
      
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
       enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
   
      
              
        
