server:
  context-path: /saw
  port: 8000
  
spring:
  sleuth:
    sampler:
      percentage: 0.1

metadata:
     url : http://mapr-dev01.sncrbda.dev.vacum-np.sncrcorp.net:9200      
     context: /md
analysis:
     url: http://mapr-dev01.sncrbda.dev.vacum-np.sncrcorp.net:9200
     context: /analysis
client:
   context:
       security: /saw-security   

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false  

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
       enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
      
      
  
