info:
  component: Synchronoss Data export Service
spring:
  application:
    name: saw-export-service
server:
  address: localhost
  port: 9400
  context-path: ''
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json    

analysis:
    service:
        host: https://saw.bda.poc.velocity-va.synchronoss.net/services/analysis
    size: 10000

       
