DROP TABLE IF EXISTS CONTACT_INFO;

CREATE TABLE CONTACT_INFO
(
  CONTACT_INFO_SYS_ID BIGINT  NOT NULL,
  CUSTOMER_SYS_ID	  BIGINT NOT NULL,
  SOURCE_SYS_ID       VARCHAR(255),
  SOURCE_SYS_ID_TYPE  VARCHAR(255),
  FIRST_NAME          VARCHAR(100) NOT NULL,
  MIDDLE_NAME         VARCHAR(100),
  LAST_NAME           VARCHAR(100) NOT NULL,
  PREFIX              VARCHAR(100),
  SUFFIX              VARCHAR(100),
  TITLE               VARCHAR(255),
  EMAIL               VARCHAR(255) NOT NULL,
  EMAIL2              VARCHAR(255),
  EMAIL3              VARCHAR(255),
  PHONE_NUMBER        VARCHAR(100),
  PHONE_NUMBER2       VARCHAR(100),
  PHONE_NUMBER3       VARCHAR(100),
  FAX                 VARCHAR(255),
  FAX2                VARCHAR(255),
  FAX3                VARCHAR(255),
  PRIMARY_IND         TINYINT,
  NOTES               VARCHAR(255),
  ACTIVE_FROM_DATE    DATETIME,
  ACTIVE_THRU_DATE    DATETIME,
  CONTACT_TYPE_CODE   VARCHAR(255),
  WEB_ADDRESS1        VARCHAR(255),
  WEB_ADDRESS2        VARCHAR(255),
  WEB_ADDRESS3        VARCHAR(255),
  WEB_ADDRESS4        VARCHAR(255)
)ENGINE=InnoDB;