#!/bin/sh
#
# Update the revision property in ".mvn/maven.config".  Populates the
# parameterized Maven POM "version" property with a value calculated
# from the current Git revision.  Note: When Maven 3.5.0, which allows
# overriding property values from the command line, is available in
# Bamboo, consider setting the value from the command line instead and
# removing this script.
#
set -eu -o pipefail

dir=$(dirname $0)
revision=$(git describe --match 'v*' --long | sed -e 's/^v//')
echo "-Drevision=$revision" > $dir/maven.config
