#!/bin/sh
#
# Update the revision property in ".mvn/maven.config".  Populates the
# parameterized Maven POM "version" property with a value calculated
# from the current Git revision.  Used in continuous integration to
# build packages that are automatically versioned.
#
set -euo pipefail

dir=$(dirname $0)
revision=$(git describe --match 'v*' --long | sed -e 's/^v//')
echo "-Drevision=$revision" > $dir/maven.config
