DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
  ROLE_SYS_ID       BIGINT  NOT NULL,
  CUSTOMER_SYS_ID   BIGINT  NOT NULL,
  ROLE_NAME         VARCHAR(100) NOT NULL,
  ROLE_CODE         VARCHAR(100) NOT NULL,
  ROLE_DESC          VARCHAR(500),
  ROLE_TYPE         VARCHAR(100) NOT NULL,
  DATA_SECURITY_KEY         VARCHAR(100) NOT NULL,
  ACTIVE_STATUS_IND TINYINT NOT NULL,
  CREATED_DATE     DATETIME NOT NULL,
  CREATED_BY       VARCHAR(255)NOT NULL,
  INACTIVATED_DATE   DATETIME,
  INACTIVATED_BY     VARCHAR(255),
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY        VARCHAR(255)
)
ENGINE=InnoDB;
