- name: Install MariaDB package
  yum: name=mariadb-server state=present
- name: Install MariaDB configuration additions
  template: src=mysql-saw.cnf dest=/etc/my.cnf.d/saw.conf
- name: Enable and start MariaDB service
  systemd: name=mariadb enabled=true state=started
- name: Install Python interface to MySQL
  yum: name=MySQL-python state=present
- name: Create SAW Security group
  group: name=saw
- name: Create SAW Security user
  user: name=saw group=saw
- name: Create BDA directory
  file: path=/etc/bda state=directory
- name: Create SAW Security variables file
  template: src=saw-security.vars dest=/etc/bda/saw-security.vars
- name: Install SAW Security package
  yum: name="{{ item }}" state=present
  with_fileglob: ["../rpms/bda-saw-security-*.rpm"]
- name: Run SAW Security configuration initialization
  command: /opt/bda/saw-security/bin/conf_init
