---
title: "Regressor Template"
author: "Change Me"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message = FALSE,
                      fig.align = "center", fig.width = 9, fig.height = 5)
```

## Version Notes


```{r input-data-params, eval = FALSE}

## Input Data Parameters for reader function

# Path to dataset
dataset_path <- "CHANGEME"

# Name to assign to Data
dataset_name <- "df"

# Dataset type
dataset_type <- "CHANGEME"

```


```{r inputs, eval = FALSE}

## Regressor Configuration Inputs 

# target variable name
target <- "changeme"

# Optional Regressor name
name <- NULL

# Optional Regressor Unique ID
uid <- sparklyr::random_string("regressor")

# Optional Regressor Version 
version <- NULL

# Optional Description of Regressor
desc <- NULL

# Optional Input for Data Scientist Author
scientist <- NULL

# Execution Strategy (sequential or multisession)
execution_strategy <- "sequential"

# Option to refit model on entire training and validation sample
refit <- TRUE

# Option to save sub-models used in tuning
save_submodels <- TRUE

# Optional random seed number
seed <- 319

```


```{r regressor-creation, eval = FALSE}

# Create Regressor
r1 <- regressor(df,
                target,
                name = name,
                uid = uid,
                version = version,
                desc = desc,
                scientist = scientist,
                execution_strategy = execution_strategy,
                refit = refit,
                save_submodels = save_submodels,
                seed = seed)
```


```{r measure, eval = FALSE}

# Set Measure. RMSE is default
r1 <- set_measure(r1, RMSE)

```


```{r sampling, eval = FALSE}

# Set Sampling Method. Options include cross_validation, holdout, random or
# default
r1 <- add_holdout_samples(r1, splits = c(.6, .2, .2))

```


```{r feature-generation, eval = FALSE}

# Create one or more feature generation pipelines. Each can be applied in one or
# more models
feature_pipe1 <- pipeline(expr = identity,
                          uid  = "Feature-Pipe-1",
                          desc = "")

```


```{r models, eval = FALSE}

# Add Regression Models
r1 <- r1 %>% 
  add_model(., 
            method = "ml_linear_regression",
            pipe = feature_pipe1,
            param_map = list(standardization = TRUE),
            uid = "linear-baseline",
            desc = "Simple linear model to create baseline prediction accuracy")
```


```{r train-models, eval = FALSE}

# Train models
r1 <- train_models(r1)

```


```{r set-final, eval = FALSE}

# Set Final Model 
r1 <- set_final_model(r1, "best", reevaluate = TRUE, refit = TRUE)
```



```{r r-config, eval = FALSE}

## R Configuration Parameters

# Library Path
lib_path <- .libPaths()[1]

# R packages
packages <- c("a2munge", "a2modeler", "a2charter", "sparklyr", "dplyr", "purrr", "ggplot2")


```


```{r spark-config, eval = FALSE}

## Spark Configuration Parameters

# Create Spark Connection
spark <- TRUE

# Spark Master
spark_master <- "local"

# Spark Version
spark_version <- "2.3.0"

# Additional Spark Configuration Settings. Add configuration with named element
# in list
spark_config_args <- list(spark.memory.fraction = 0.9)

```


```{r r-setup, eval = FALSE}

# Load Libraries
for(pck in packages) library(pck, lib.loc = lib_path, character.only = TRUE)

```


```{r spark-setup, eval = FALSE}

# If Spark Option True, create connection
if(spark) {
  
  conf <- modifyList(spark_config(), spark_config_args)
  sc <- spark_connect(master = spark_master,
                      version = spark_version,
                      config = conf)
}
```


```{r data-import, eval = FALSE}

# Read data into memory
if(spark) {
  df <- reader(sc, name = dataset_name, path = dataset_path, type = dataset_type)
} else {
  df <- read.csv(dataset_path)
}

```


```{r execution, ref.label=c('r-config', 'r-setup', 'spark-config', 'spark-setup', 'input-data-params', 'data-import', 'inputs', 'regressor-creation', 'measure', 'sampling', 'feature-generation', 'models', 'train-models', 'set-final')}

```


```{r regressor-print, echo=FALSE, results='asis'}
cat("##", r1$name, "Regressor", "\n")

```

* uid: __`r r1$uid` __ 
* Version: __`r r1$version`__  
* Created on: __`r as.character(r1$created_on)`__ 
* Created by: __`r r1$scientist`__
* Description: _`r r1$desc`_  


```{r data-print, echo=FALSE, results='asis'}
cat("###", "Input Data:", dataset_name,"\n")

```

* Location: __`r dataset_path`__
* Type: __`r dataset_type`__


#### Sample Records


```{r sample-records, echo=FALSE}

# Datatable with sample records
r1$data %>% 
  collecter(sample = TRUE, method = "head", size = 100) %>% 
  DT::datatable(.,
                options = list(scrollX = TRUE),
                caption = paste(dataset_name, "Sample Records"))
```


```{r target-print, echo=FALSE, results='asis'}
cat("###", "Target:", r1$target,"\n")

```


```{r target-summary, echo=FALSE}

df %>%
  a2munge::collecter(sample = TRUE, method = "head", size = 1000) %>% 
  a2charter::gg_histogram(.,
                          r1$target,
                          title = paste(paste0(r1$name, ":"), r1$target))

df %>%
  dplyr::summarise_at(target, funs(min, mean, sd, max)) %>% 
  knitr::kable(., 
               digits = 3,
               caption = paste(paste0(r1$name, ":"), r1$target, "Summary"))
```


### Pipelines


```{r pipeline-print, echo=FALSE}
for(p in seq_along(r1$pipelines)) {
  print(r1$pipelines[[p]])
}
```


### Models


```{r models-print, echo=FALSE, results='asis'}

for(i in seq_along(r1$models)) {
  cat("####", names(r1$models)[i])
  cat("\n")
  cat("* Method:", paste0("__", r1$models[[i]]$method, "__"), "\n")
  cat("* Package:", paste0("__", r1$models[[i]]$package, "__"), "\n")
  cat("* Pipeline:", paste0("__", r1$models[[i]]$pipe, "__"), "\n")
  cat("* Status:", paste0("__", r1$models[[i]]$status, "__"), "\n")
  cat("* Last Updated:", paste0("__", r1$models[[i]]$last_updated, "__"), "\n")
  cat("\n")
  
  cat("##### Parameter Tuning:\n")
  for(p in seq_along(r1$models[[i]]$param_map)) {
    cat("*",
        paste0(names(r1$models[[i]]$param_map)[p], ":"),
        paste(r1$models[[i]]$param_map[[p]], collapse = ", "),
        "\n")
  }
  cat("\n")
}

```


### Leaderboard


```{r leaderboard}
r1$performance %>% 
  dplyr::select(model_uid, pipeline_uid, method, param_grid, sample, !!r1$measure$method) %>% 
  dplyr::arrange_at(r1$measure$method) %>% 
  knitr::kable(.,
               digits = 3,
               caption = paste(r1$name, "Model Leaderboard"))
```


### Final Model


```{r final-model, results='asis'}

cat("* uid:", paste0("__", r1$final_model$uid, "__"), "\n")
cat("* Method:", paste0("__", r1$final_model$method, "__"), "\n")
cat("* Package:", paste0("__", r1$final_model$package, "__"), "\n")
cat("* Status:", paste0("__", r1$final_model$status, "__"), "\n")
cat("* Last Updated:", paste0("__", r1$final_model$last_updated, "__"), "\n")
cat("\n")

```


```{r final-model-params}

r1$final_model$fit$stages[[2]]$param_map %>%
  as.data.frame() %>%
  tidyr::gather(key = "parameter") %>% 
  dplyr::filter(! grepl("_col|seed", parameter)) %>% 
  knitr::kable(.,
               table.attr = "style='width:30%;'",
               caption = "Final Model Parameters")
```


```{r test-fit-print, results='asis'}
if(! is.null(r1$samples$test_holdout_prct)) {
  cat("#### Test Holdout Fit\n")
  cat("Final Model Performance on Test Holdout:\n\n")
  cat("*", r1$measure$method, "=", round(r1$final_model$test_performance[[1]], 3), "\n")
}
```


```{r test-resid}
if(! is.null(r1$samples$test_holdout_prct)) {
  tpdf <- r1$final_model$test_predictions %>% 
    a2munge::collecter(., sample = TRUE, method = "head", size = 1000) 
  
  pred_var <- setdiff(colnames(tpdf), r1$target) 
  
  tpdf <- tpdf %>% 
    dplyr::mutate(residual = !!rlang::sym(pred_var) - !!rlang::sym(r1$target))
  
  plt1 <- a2charter::gg_scatter_chart(tpdf,
                                      pred_var,
                                      r1$target,
                                      alpha = .5,
                                      smoother = TRUE,
                                      smooth_method = "lm",
                                      smooth_color = "red",
                                      smooth_ci = FALSE) +
    ggplot2::geom_abline(slope = 1, intercept = 0, linetype = 5, color = "grey50")
  
  plt2 <- a2charter::gg_scatter_chart(tpdf,
                                      pred_var,
                                      "residual",
                                      alpha = .5,
                                      smoother=FALSE)  +
    ggplot2::geom_hline(yintercept = 0, linetype = 5, color = "grey50")
  
  gridExtra::grid.arrange(plt1, plt2, ncol=2)
}
```



## Configuration

```{r regressor-config, echo=TRUE, eval=FALSE, ref.label=c('inputs', 'regressor-creation', 'measure', 'sampling', 'feature-generation', 'models', 'train-models', 'set-final')}

```


## Appendix

```{r config, echo=TRUE, eval=FALSE, ref.label=c('r-config', 'spark-config')}

```
