= SAW Design Guide
Version {project-version}
:toc:
:nofooter:
:docinfo: shared
:plantuml-config: plantuml-config

== Introduction

This document describes the high-level design of the SAW application,
including its architecture and modules.

== Overview

The application consists of three modules: SAW Web, SAW Services and
SAW Security.  SAW Web provides a web application for creating and
executing analysis.  It builds on top of SAW Services, which provides
a REST API for creating and executing analyses.  SAW Security manages
authentication and privileges of users.

.Figure: SAW modules and their dependencies
plantuml::saw-design/figure-modules.pum[format=svg]

The modules can be taken into use independently, as long as their
dependencies are also provided.  Typically all three modules are used
together.

.Figure: External SAW interfaces and their use
plantuml::saw-design/figure-interfaces.pum[format=svg]

== SAW Web

The SAW Web module provides a user interface for creating and
executing analyses.  It is implemented it AngularJS and makes calls to
the SAW Services REST API over HTTP.  It additionally calls SAW
Security to authenticate users and manage privileges.

The SAW Web user interface is organized into two modules: analyze and
observe.  Additionally it provides a user interface for managing users
and privileges in SAW Security.

== SAW Services

SAW Services are a collection of microservices exposed over HTTP REST
APIs.  They enable creating and executing analyses.  They are
implemented in Java and the Spring Framework.  As an exception, the
SAW Transport Service is implemented in Scala and the Play framework.

.Figure: SAW Services and their dependencies
plantuml::saw-design/figure-services.pum[format=svg]

SAW Services use MapR-DB for persistence, using the OJAI interface.
As an exception, the SAW Transport Service uses the MapR-DB binary
tables.  Additionally SAW Services access files on the MapR-FS.

=== SAW Gateway Service

The SAW Gateway Service acts as single entry point for all upstream
micro services.  It is a Spring Boot based microservice. It upholds
the concerns regarding security.  It acts as edge service and
authenticates every request that passes by it nad makes sure that it
is valid.  In addition to these, it comes with the following benefits:

. Insulates the clients from how the application is partitioned into
  micro-services

. Insulates the clients from the problem of determining the locations
  of service instances

. Provides the optimal API for each client

. Reduces the number of requests/roundtrips.  For example, the API
  gateway enables clients to retrieve data from multiple services with
  a single round-trip.  Fewer requests also means less overhead and
  improves the user experience.  An API gateway is essential for
  mobile applications.

. Simplifies the client by moving logic for calling multiple services
  from the client to API gateway

. Translates from a "standard" public web-friendly API protocol to
  whatever protocols are used internally

The SAW gateway pattern has some drawbacks:

. Increased complexity - the API gateway is yet another moving part
  that must be developed, deployed and managed.

. Increased response time due to the additional network hop through
  the API gateway - however, for most applications the cost of an
  extra roundtrip is insignificant.

=== SAW Dataset Service

The SAW Dataset Service provides starting points for creating
analyses.  Administrators load information about datasets (including
so called semantic metadata) into SAW, which is used to create
analyses.  The information about datasets includes the location of the
data, its schema in the form of columns, data types of columns and
so on.  Clients can enumerate datasets and retrieve descriptions of
them for use when creating analyses.

=== SAW Analysis Service

The SAW Analysis Services allows creating, reading, updating and
deleting analyses.  Analyses are used to execute queries on data.  An
analysis is created based on information about a dataset, also known
as semantic metadata.  An analysis can contain one or more artifacts,
each of which contain a set of columns.  Each column in an analysis
has a number of properties, for example if it is selected, or joined
with another column.  These properties affect how the analysis is
translated into a query that is exected.

=== SAW Execution Service

The SAW Execution Service enables executing analyses.  It takes an
analysis to execute as input, translates it into a query and executes
the query and finally provides the results back to the client.

.Figure: Executing an analysis using the SAW Execution Service
plantuml::saw-design/figure-execution-sequence.pum[format=svg]

The SAW Execution Service supports two types of storage: Apache Spark
and Elasticsearch.  Analyses of type report are executed on Apache
Spark clusters, while analyses of type pivot and chart are executed on
Elasticsearch clusters.

==== Apache Spark

The Apache Spark executor supports analyses of type report.

Reports are executed as Spark SQL queries running on an Apache Spark
cluster.  The queried data is stored as Parquet files in the data
lake.  The report execution functionality is provided by two
components: the Transport Service and the Transport Service Executor.

The Transport Service provides an internal REST API for SAW Web to
use, including operations to execute a report.  When a report is
executed, the Transport Service writes a message requesting execution
to a message queue.  The message queue is implemented using MapR
streams.  The Transport Service Executor consumes messages from the
queue and executes queries accordingly.

Executors are run in two different modes: fast and regular.  The fast
executors read from the fast queue to which preview and onetime
executions are sent, with expectations of lower latency using
techniques such as preallocated Spark contexts.  The regular executors
read from the regular queue to which scheduled executions are sent.
Using two different queues limits the resources provided to
potentially heavy and long-running scheduled executions to avoid
blocking the more time-sensitive preview and onetime executions.

The queue approach with executors in separate processes is used due to
the limitation of having one Spark context per Java virtual machine.
The number of executors of each type is configured statically in the
SAW environment configuration and used during deployment.  The report
execution concurrency limit follows from the number of executors
configured for each type.

As a preventive measure, executors restart the Java virtual machine
after handling an execution.  This avoids building up state between
executions that can be a source of errors.

When an analysis of type report is executed by the Transport Service,
the results are stored as newline-delimited JSON in the data lake.
When results need to be read back by the Transport Service, it reads
the newline-delimited JSON file in the data lake over the MapR-FS.
The results can then be streamed to avoid reading the entire results
into memory at the same time which might lead to out of memory errors.

==== Elasticsearch

The Elasticsearch executor supports analyses of types pivot and chart.

=== SAW Export Service

The SAW Export Service enables exporting analysis executions to file
formats such as Microsoft Excel.  It calls the SAW Execution Service
to retrieve the execution result, generates the desired output file
format and finally provides it to the client.

=== SAW Scheduler Service

The SAW Scheduler Service triggers execution of analyses
based on their configured schedule.  The SchedulerService is a Spring
Boot based micro-service, which provides Api to create, manage and trigger schedules.
It also triggers dispatch request to saw-export service, if analysis execution result
needs to be dispatched.

Internally it uses the Quartz scheduler framework for create, manage and trigger
analysis schedules with mariaDB as job store. The Scheduler Service
does not monitor the actual execution or its results, but only
triggers the start of execution.


=== SAW Observe Service

The SAW Observe Service enables creating, reading, updating and
deleting dashboards.

== SAW Security

The SAW Security module provides authentication and privilege services
to other modules.  It is implemented as a microservice in Java and the
Spring Framework and uses a MariaDB database to persist authentication
and privilege information.

.Figure: The SAW Security Service and dependencies
plantuml::saw-design/figure-security.pum[format=svg]

A client authenticated to the SAW Security Service by sending a to the
REST API.  The credentials and privileges are checked against the SAW
Security database, after which a token is issued and returned in the
response to the client.

.Figure: Authenticating a client using the SAW Security Service
plantuml::saw-design/figure-security-sequence.pum[format=svg]
