#!/bin/sh
#
# Deploy SAW Services to the shared development environment
#

error() {
    echo "Error: $*"
    exit 1
}

if ! command -v ansible-playbook > /dev/null; then
    error "Ansible not found; please install and retry"
fi

cd $(dirname $0)
ansible-playbook -i ansible/hosts ansible/playbook.yml
