#!/bin/sh
#
# Package SAW modules in a single package for convenience.  Assumes
# any SAW modules to be packaged togehter have been put in
# "target/saw-*.tgz".
#
set -eu

dir=$(dirname $0)
cd $dir/target

# Extract parent SAW package
tar -xzf saw-2*.tgz
rm saw-2*.tgz
mv saw-2* saw
mkdir saw/modules

# Add SAW modules
cd saw/modules
for module in saw-security saw-services; do
    tar -xzf ../../$module-*.tgz
    ln -s $module-* $module
done
cd ../..

# Archive the SAW parent package again
tar -czf saw.tgz saw
