/*******************************************************************************
 Create Workbench module and "My Workflow" as default sub category
********************************************************************************/
INSERT INTO `MODULES` (`MODULE_SYS_ID`,`MODULE_NAME`,`MODULE_CODE`,`MODULE_DESC`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (5,'WORKBENCH','WRK000001','Workbench Module',1,NOW(),'admin');
-- Correcting module (spelling mistake)
UPDATE MODULES SET MODULE_DESC='Analyze Module' WHERE MODULE_CODE= 'ANLYS00001';
-- Binding Product & Module
INSERT INTO `PRODUCT_MODULES` (`PROD_MOD_SYS_ID`,`PRODUCT_SYS_ID`,`MODULE_SYS_ID`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (9,4,5,1,NOW(),'admin');
-- Binding Product, Module & Customer
INSERT INTO `CUSTOMER_PRODUCT_MODULES` (`CUST_PROD_MOD_SYS_ID`,`CUST_PROD_SYS_ID`,`PROD_MOD_SYS_ID`,`CUSTOMER_SYS_ID`,`ACTIVE_STATUS_IND`,`MODULE_URL`,`DEFAULT`,`CREATED_DATE`,`CREATED_BY`) VALUES (4,1,9,1,1,'/',0,NOW(),'admin');
-- take values from above query and put them in privileges
INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_FEATURE_SYS_ID`,`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES ('21',4,'/','Workflow','Workflow','WORKBENCH52','PARENT_WORKBENCH52',0,1,NOW(),'admin');
SELECT @CUSTOMER_PROD_MOD_SYS_ID_1 := CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE='WORKBENCH52';
INSERT INTO `PRIVILEGES` (`PRIVILEGE_SYS_ID`, `CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES ('101', '1', @CUSTOMER_PROD_MOD_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_1, '1', '0', '128', 'All', '1', NOW(), 'admin');
-- take values from above query and put them in privileges
INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_FEATURE_SYS_ID`,`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES ('22',4,'/','My Workflow','My Workflow','MYWORKBENCH52','CHILD_WORKBENCH52',0,1,NOW(),'admin');
SELECT @CUSTOMER_PROD_MOD_SYS_ID_1 := CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE='MYWORKBENCH52';
INSERT INTO `PRIVILEGES` (`PRIVILEGE_SYS_ID`, `CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES ('102', '1', @CUSTOMER_PROD_MOD_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_1, '1', '0', '128', 'All', '1', NOW(), 'admin');
-- Updating USER table
UPDATE USERS SET EMAIL = 'sysadmin@synchronoss.com' , FIRST_NAME ='system' , MIDDLE_NAME='sncr', LAST_NAME='admin', MODIFIED_BY = NOW() WHERE USER_ID='sawadmin@synchronoss.com';
UPDATE USERS SET EMAIL = 'sysadmin@synchronoss.com' , FIRST_NAME ='system' , MIDDLE_NAME='sncr', LAST_NAME='admin', MODIFIED_BY = NOW() WHERE USER_ID='reportuser@synchronoss.com';
UPDATE USERS SET EMAIL = 'sysadmin@synchronoss.com' , FIRST_NAME ='system' , MIDDLE_NAME='sncr', LAST_NAME='admin', MODIFIED_BY = NOW() WHERE USER_ID='analyst@synchronoss.com';
UPDATE USERS SET EMAIL = 'sysadmin@synchronoss.com' , FIRST_NAME ='system' , MIDDLE_NAME='sncr', LAST_NAME='admin', MODIFIED_BY = NOW() WHERE USER_ID='reviewer@synchronoss.com';
