- name: SAW Security (MariaDB Galera cluster arbitrator)
  hosts: saw-security-arbitrator
  become: true
  roles:
    - sip-security-db-arbitrator
- name: SAW Security
  hosts: saw-security
  become: true
  roles:
    - sip-common-utils
    - sip-security-db
    - sip-security-web

