#!/bin/bash
###########################################################################
# semanticIdMigration
# Author: Alok KumarR
# Creation Date: JUNE 4 2019
###########################################################################


NOW=$(date +"%m-%d-%Y %r")

BASE_PATH=${1}  # eg: maprfs:///var/sip3

# Fetch the list of mapr libraries
MAPR_LIB_PATH=$(mapr classpath)

METADATA_SERVICE_DIR="/opt/bda/sip-metadata-service"
JAR_FILE="sip-metadata.jar"
MIGRATION_CLASS="com.synchronoss.saw.analysis.service.migrationservice.SemanticIdMigrationUtility"

echo
echo
echo SEMANTIC ID MIGRATION STARTING AT $NOW
echo ---------------------------------------------------------------------
echo Table Base Path             :            ${BASE_PATH}
echo ---------------------------------------------------------------------
echo
CMD="java -cp ${METADATA_SERVICE_DIR}/${JAR_FILE}:${MAPR_LIB_PATH} -Dloader.main=${MIGRATION_CLASS} org.springframework.boot.loader.PropertiesLauncher $@"

echo "Running ${CMD}"

sudo su mapr -c "$CMD"
RETVAL=$?
echo ---------------------------------------------------------------------
echo JOB RETURN CODE:  $RETVAL
echo ---------------------------------------------------------------------
exit $RETVAL
