info:
  component: Synchronoss Semantic Service
spring:
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
  application:
    name: saw-semantic-service
logging:
  level:
    com.synchronoss.saw.semantic: INFO
    org.springframework: INFO
    sncr.bda: INFO
server:
  servlet:
    context-path: ''
  address: localhost
  port: 9901
  
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000

metastore:
    base:  hdfs:///main/
semantic:
    workbench-url:  http://localhost:9700
    transport-metadata-url:  http://localhost:9200
    binary-migration-requires: false
    migration-metadata-home: /var/sip/
    