info:
  component: Synchronoss Data export Service
spring:
  application:
    name: saw-export-service
  mail:
     host: outgoing.sncrcorp.net
     port: 25
     protocol: smtp
     test-connection: false
     username:
     password:
     smtp:
      auth: false
     properties:
      mail.smtp.from: SAWReport@synchronoss.com
      # To do : Mail body can be moved to maprdb to configure email custom template from UI for saw customers level.
     body: "Hello  </br> Attached is an analysis for your review.</br>Analysis Name: $analysis_name </br>Analysis Description: $analysis_description </br>Publish Time : $publish_time </br> Analysis Created By: $created_by </br> </br>Regards,<br>Synchronoss Analytics Team </br>"
server:
  address: localhost
  port: 9400
  servlet:
    context-path: ''
  #ssl:
   # key-store: /Users/spau0004/Desktop/keystore/keystore.jks
   # key-store-password: sip@123
   # trust-store: /Users/spau0004/Desktop/keystore/truststore.jks 
   # trust-store-password: sip@123  
  max-http-header-size:  65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json    

analysis:
    uiExportSize: 10000
    emailExportSize: 50000
    ftpExportSize: 100000
    s3ExportSize: 1000000

proxy:
    service:
        host: http://localhost:9800

metadata:
  service:
    host: http://localhost:9501

published:
  path: /tmp


ftp:
  details:
    file: /opt/bda/saw-export-service/conf/ftp-details.json
    privatekeyDir: /etc/bda/sftpkeys

s3:
  details:
    file: /opt/bda/saw-export-service/conf/S3-details.json

exportChunkSize: 10000

sip:
   ssl:
     enable : false
   trust:
       store: /Users/spau0004/Desktop/keystore/truststore.jks
       password: sip@123
   key:
      store: /Users/spau0004/Desktop/keystore/keystore.jks
      password: sip@123

