#!/bin/bash

set -eu

declare -r sip_executor_home=/opt/bda/sip-executor
# Create ':' separated list of all files in $lib_dir
declare lib_classpath=

for i in `ls ${sip_executor_home}/lib/*.jar`; do
lib_classpath=${lib_classpath}:"${i}"
done

for j in `ls /opt/mapr/spark/spark-2.3.2/jars/*.jar`; do
 lib_classpath=${lib_classpath}:"${j}"
done

lib_classpath=${lib_classpath}:$(mapr classpath):$(hadoop classpath)

declare -r conf_dir="${sip_executor_home}/conf"
( cd $conf_dir ) || exit

CMD="exec java $JAVA_OPTS -Dconfig=$conf_dir -Dlogger.file=$conf_dir/logback.xml \
     -Djava.security.auth.login.config=/opt/mapr/conf/mapr.login.conf \
     -cp $lib_classpath com.synchronoss.saw.executor.DlExecutor"

$CMD
RETVAL=$?
