#!/bin/sh
#
# Build SIP Advanced Analytics R packages
#
set -eu

# The SIP revision is passed in as a parameter, to be used in the R
# package descriptions
revision="$1"
revision_nohash=${revision%-g*}
version=${revision_nohash/-/.}

dir=$(dirname $0)
cd $dir

# Iterate through each R package to be built, build it, run tests and
# package
for dir in a2charter a2munge a2modeler a2sipr; do
    pushd $dir > /dev/null
    
    # If version is "2", skip updating the R package description as it
    # is an ad-hoc Maven invocation
    if [ "$version" != "2" ]; then
        sed -i -e "s/0\.0\.0\.9000/$version/" DESCRIPTION
    fi

    Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

    # Build package
    R CMD build .
    
    # Check package
    R CMD check *.tar.gz
    
    # Note: Skip a2modeler tests until fixed                        
    #if [ $dir != a2modeler ]; then
    #    R CMD check *.tar.gz
    #fi
    
    # Copy the R package build artifacts into the target directory,
    # which is used for copying them out of the Docker container
    cp *.tar.gz ../target
    
    # Install the built R package locally, for use by other R packages
    # later in the build process
    R CMD INSTALL *.tar.gz
    popd > /dev/null
done
