info:
  component: Synchronoss Alert Service
spring:
  application:
    name: sip-alert-service
  #mariaDB (metadata) DB details
  datasource:
    url: jdbc:mariadb://localhost:3306/sip_alert
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    max-active: 25
    testOnBorrow: true
    testOnConnect: true
    testOnReturn: true
    validationQuery: SELECT 1
    testWhileIdle: true
    logValidationErrors: true
flyway.baselineOnMigrate: true
logging:
  level:
    com.synchronoss.sip: INFO
    org.springframework: INFO
    org.hibernate.type : INFO

server:
  address: localhost
  port: 9620
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
sip:
  service:
    index: 0

