info:
  component: Synchronoss Workbench Service
spring:
  main:
    banner-mode: 'off'
  application:
    name: saw-workbench-service
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
      file-size-threshold: 2KB
logging:
  level:
    org.springframework: INFO
    com.synchronoss.saw.workbench: DEBUG
    com.synchronoss.bda: DEBUG
    org.apache.http.client: INFO
server:
  address: localhost
  port: 9701
  servlet:
    context-path: ''
  max-http-header-size:  65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

 
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000

  
sip:
  ssl:
    enable : false



connector : http


workbench:
        project-key: "workbench"
        project-path: "/workbench"
        project-root: "maprfs:///var/sip"
        preview-limit: 100
        livy-uri: "http://sip-mapr:8998/"
        storage-uri: ${connector}://localhost:9800
        app-name: SIP-workbench
        lib.path: /opt/bda/saw-workbench-service/lib/
metastore:
    base: "maprfs:///var/sip"
    
spark:
  master: yarn
  executor.memory: "2G"
  cores.max: "2"
  executor.cores: "2"
  driver.memory: "2G"
  hadoop.yarn.resourcemanager.hostname: "mapr-rd612.eng-sip.dev01.us-west.sncrcloud.net"
  yarn.jars: "/opt/mapr/spark/spark-2.3.2/jars"
  yarn.archive: "/opt/bda/sip-executor/spark.zip"
  executor.instances: "1"
  driver.port: 
  driver.host: 
  driver.bindAddress: 
  driver.blockManager.port: 
  sql.inMemoryColumnarStorage.compressed: true
  sql.inMemoryColumnarStorage.batchSize: 20 
  sql.caseSensitive: false
  ui.enabled: false
  
workbench-executor: 
  jar-location: /opt/bda/saw-workbench-service/lib
  
  
  
  
 