info:
  component: Synchronoss Workbench Service
spring:
  application:
    name: saw-workbench-service
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
      file-size-threshold: 2KB
logging:
  level:
    com.synchronoss.saw.workbench: INFO
    sncr.bda: INFO
server:
  address: localhost
  port: 9701
  servlet:
    context-path: ''
  #ssl:
   # key-store: /Users/spau0004/Desktop/keystore/keystore.jks
   # key-store-password: sip@123
   # trust-store: /Users/spau0004/Desktop/keystore/truststore.jks 
   # trust-store-password: sip@123  
  max-http-header-size:  65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000

connector: http
workbench:
        project-key: "workbench"
        project-path: "/Desktop" 
        project-root: "/Users/spau0004"
        preview-limit: 10000
        livy-uri: http://localhost:8998
        storage-url: ${connector}://localhost:9800

metastore:
    base:  hdfs:///main/   

sip:
   ssl:
     enable : false
   trust:
       store: /Users/spau0004/Desktop/keystore/truststore.jks
       password: sip@123
   key:
      store: /Users/spau0004/Desktop/keystore/keystore.jks
      password: sip@123
         
