info:
  component: Synchronoss Workbench Service
spring:
  main:
    banner-mode: 'off'
  application:
    name: saw-workbench-service
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
      file-size-threshold: 2KB
logging:
  level:
    org.springframework: INFO
    com.synchronoss.saw.workbench: DEBUG
    com.synchronoss.bda: DEBUG
    org.apache.http.client: INFO
server:
  address: localhost
  port: 9701
  servlet:
    context-path: ''
  max-http-header-size:  65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

 
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000

  
sip:
  ssl:
    enable : false



connector : http


workbench:
        project-key: "workbench"
        project-path: "/workbench"
        project-root: "maprfs:///var/sip"
        preview-limit: 100
        livy-uri: "http://sip-mapr:8998/"
        storage-uri: ${connector}://localhost:9800
metastore:
    base: "maprfs:///var/sip"