info:
  component: Synchronoss scheduler Service
spring:
  application:
    name: saw-sechduler-service
  #mariaDB (metadata) DB details
  datasource:
    url: jdbc:mariadb://localhost:3306/saw_scheduler
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    max-active: 103
    testOnBorrow: true
    testOnConnect: true
    testOnReturn: true
    validationQuery: SELECT 1
    testWhileIdle: true
    logValidationErrors: true
  flyway:
    baseline-on-migrate: true

server:
  address: localhost
  port: 9601
  servlet:
    context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

  ssl:
    key-store: /Users/spau0004/Desktop/keystore/keystore.jks
    key-alias: sipcert
    key-store-password: sip@123
    trust-store: /Users/spau0004/Desktop/keystore/truststore.jks
    trust-store-password: sip@123

management:
#  server:
#    ssl:
#      enabled: true
#      key-store: /Users/spau0004/Desktop/keystore/keystore.jks
#      key-alias: sipcert
#      key-store-password: sip@123
#      trust-store: /Users/spau0004/Desktop/keystore/truststore.jks
#      trust-store-password: sip@123
#    port: 9602
      
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
    
    
sip:
 service:
   index: 0
 ssl:
    enable : true
 trust:
     store: /Users/spau0004/Desktop/keystore/truststore.jks
     password: sip@123
 key:
    store: /Users/spau0004/Desktop/keystore/keystore.jks
    password: sip@123
   
connector: http

saw-analysis-service-url: ${connector}://localhost:9200/analysis
sip-metadata-service-url: ${connector}://localhost:9501/dslanalysis
sip-analysis-proxy-url: ${connector}://localhost:9800/internal/proxy/storage
saw-dispatch-service-url: ${connector}://localhost:9400/exports
bis-transfer-url: ${connector}://localhost:9642/ingestion/batch/channel/transfers/data
sip-dispatch-row-limit: 10000

encryption:
  key: 20-89-C3-13-D6-29-9E-91-6C-35-C2-4D-0A-B5-2C-D4
       
