info:
  component: SIP metadata Service
spring:
  application:
    name: sip-metadata-service
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
      file-size-threshold: 2KB
logging:
  level:
    com.synchronoss.saw: INFO
    org.springframework: INFO
    sncr.bda: INFO
server:
  address: localhost
  port: 9501
  servlet:
    context-path: ''
  max-http-header-size:  65536
  ssl:
    key-store: /Users/spau0004/Desktop/keystore/keystore.jks
    key-alias: sipcert
    key-store-password: sip@123
    trust-store: /Users/spau0004/Desktop/keystore/truststore.jks 
    trust-store-password: sip@123  
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000

metastore:
  base:  hdfs:///main/
  
connector: https  
semantic:
  workbench-url:  ${connector}://localhost:9700
  transport-metadata-url:  ${connector}://localhost:9642
  binary-migration-requires: false
  migration-metadata-home: /var/sip/
  
sip:
   ssl:
     enable : true
   trust:
       store: /Users/spau0004/Desktop/keystore/truststore.jks
       password: sip@123
   key:
      store: /Users/spau0004/Desktop/keystore/keystore.jks
      password: sip@123
  
