#!/bin/sh
#
# Start SAW deployment for container
#
set -eu

# Save SAW system logs to build directory in case needed for
# troubleshooting after a failed run
trap "journalctl -u saw-* > /build/saw-system.log" EXIT

cd /maven
tar -xzf saw.tgz
saw/saw-deploy /root/saw-config
