info:
  component: Synchronoss Alert Service
spring:
  application:
    name: sip-alert-service

logging:
  level:
    com.synchronoss.sip: INFO
    org.springframework: INFO
    org.hibernate.type : INFO

server:
  address: localhost
  port: 9621
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
sip:
  service:
    index: 0
  ssl:
    enable : false
mail:
  body: "Hello  </br> Below details contains information about the alert generated.</br>Alert Name: $alertName </br>Category: $category </br>Link for the alert Dashboard : $link </br> Alert Severity: $alertSeverity </br> </br>Regards,<br>Synchronoss Analytics Team </br>"
  subject : "Alert Notification"
alert:
  dashborad:
    url: http://35.175.174.29/sip/web/#/alerts/view
storage-proxy:
  service:
    host: http://localhost:9400
metastore:
  base:  maprfs:///var/sip/
  alertRulesTable: alertRulesMetadata
  alertResults: alertResults
  notificationTable : alertNoficationLog
