#!/bin/bash
#
# Run initial database setup
#
set -eu

dir=$(dirname $0)

# Use a marker file to ensure database setup is only run once, until
# automatic migration (including initial setup) is implemented
marker=/etc/bda/saw-security-initial-setup
if [ -f $marker ]; then
    echo "Initial database setup has already been run, so not running again"
    echo "(Marker file: $marker)"
    exit
fi
touch $marker

# Create database users
mysql -u root < $dir/init.sql
create_user="CREATE USER 'saw_security'@'localhost'"
password=$(< /etc/bda/saw-security-db-password)
mysql -u root -e "$create_user IDENTIFIED BY '$password'"
mysql -u root -e "GRANT ALL ON saw_security.* TO 'saw_security'@'localhost'"

# Set root password
set -o pipefail
password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 14)
password_file=/etc/bda/mariadb-root-password
echo $password > $password_file
chmod u+rw,go= $password_file
mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$password')"

# Populate database
python $dir/Initial_Setup.py --vars
