info:
  component: Synchronoss Batch Ingestion Service
spring:
  application:
    name: saw-batch-ingestion-service
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sip_bis
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true

logging:
  level:
    com.synchronoss.saw: INFO
    org.springframework: INFO
    org.hibernate.type.descriptor.sql.BasicBinder : INFO
    org.hibernate.SQL: INFO
    org.springframework.retry: INFO

server:
  address: localhost
  port: 9642
  servlet:
    context-path: ''
  maxHttpHeaderSize:  65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  ssl:
    key-store: /Users/spau0004/Desktop/keystore/keystore.jks
    key-alias: sipcert
    key-store-password: sip@123
    trust-store: /Users/spau0004/Desktop/keystore/truststore.jks
    trust-store-password: sip@123

management:
#  server:
#    ssl:
#      enabled: true
#      key-store: /Users/spau0004/Desktop/keystore/keystore.jks
#      key-alias: sipcert
#      key-store-password: sip@123
#      trust-store: /Users/spau0004/Desktop/keystore/truststore.jks
#      trust-store-password: sip@123
#    port: 9643
      
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, prometheus

application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
sip:
  service:
    index: 0
    max.attempts : 3
    retry.delay: 5000
    retry.diff.mins: 5
    retry.page.size: 20
    max.inprogress.mins: 45
    max.inprogress.job.mins: 60
    worker.delay: 5000
  transfer:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
  retry:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
  ssl:
    enable : true
  trust:
     store: /Users/spau0004/Desktop/keystore/keystore.jks
     password: sip@123
  key:
     store: /Users/spau0004/Desktop/keystore/truststore.jks
     password: sip@123
     
  
connector: https


bis:
  transfer-batch-size: 10
  modified-retries: 3
  default-data-drop-location: "/Users/spau0004/Desktop/workbench"
  scheduler-url: ${connector}://localhost:9601
  recheck-file-modified: false
  destination-fs-user: mapr
  duplicate-entry: true
 
  

