#!/bin/sh
#
# Start SAW deployment for container
#
set -eu

# Save SAW system logs to build directory in case needed for
# troubleshooting after a failed run
trap "journalctl -u saw-\* > /build/saw-system.log" EXIT

cd /maven
tar -xzf saw-*.tgz

# Workaround: Building on Windows causes execute permissions on files
# getting lost, and the permissions "auto" setting on the Docker Maven
# plug-in does not seem to help, so set the execute bit explicitly
# here as a workaround.
chmod a+x saw/saw-deploy

saw/saw-deploy /root/saw-config

# If deploying to the cloud, log the SAW start page URL as a
# convenience
aws_metadata_url=http://169.254.169.254/latest/meta-data/public-hostname
public_hostname=$(curl $aws_metadata_url 2>/dev/null)
if [ -n "$public_hostname" ]; then
    echo "SAW start page URL: http://$public_hostname/"
fi
