DROP TABLE IF EXISTS CUSTOMER_PRODUCT_MODULE_FEATURES;

CREATE TABLE CUSTOMER_PRODUCT_MODULE_FEATURES
(
  CUST_PROD_MOD_FEATURE_SYS_ID      BIGINT  NOT NULL,
  CUST_PROD_MOD_SYS_ID      		 BIGINT  NOT NULL,
  DEFAULT_URL     					 VARCHAR(500)  NOT NULL,
  FEATURE_NAME	                     VARCHAR(100),
  FEATURE_DESC                       VARCHAR(500),
  ACTIVE_STATUS_IND                  TINYINT NOT NULL,
  CREATED_DATE    					 DATETIME NOT NULL,
  CREATED_BY       					 VARCHAR(255)NOT NULL,
  INACTIVATED_DATE   				 DATETIME,
  INACTIVATED_BY                     VARCHAR(255),
  MODIFIED_DATE     				 DATETIME,
  MODIFIED_BY        				 VARCHAR(255)
)ENGINE=InnoDB;

  
  
  
