DROP TABLE IF EXISTS CUSTOMER_PRODUCT_MODULES;

CREATE TABLE CUSTOMER_PRODUCT_MODULES
(
  CUST_PROD_MOD_SYS_ID      BIGINT  NOT NULL,
  CUST_PROD_SYS_ID      BIGINT  NOT NULL,
  PROD_MOD_SYS_ID      BIGINT  NOT NULL,
  CUSTOMER_SYS_ID      BIGINT  NOT NULL,
  ACTIVE_STATUS_IND    TINYINT NOT NULL,
  CREATED_DATE     DATETIME NOT NULL,
  CREATED_BY       VARCHAR(255)NOT NULL,
  INACTIVATED_DATE   DATETIME,
  INACTIVATED_BY     VARCHAR(255),
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY        VARCHAR(255)
)ENGINE=InnoDB;

