DROP TABLE IF EXISTS ROLE_PRIVILEGES;
CREATE TABLE ROLE_PRIVILEGES
(
  ROLE_PRIVILEGES_SYS_ID   BIGINT  NOT NULL,
  ROLE_SYS_ID              BIGINT  NOT NULL,
  PRIVILEGE_SYS_ID         BIGINT  NOT NULL,
  ACTIVE_STATUS_IND 	   TINYINT NOT NULL,
  CREATED_DATE   		   DATETIME NOT NULL,
  CREATED_BY               VARCHAR(255)NOT NULL,
  INACTIVATED_DATE         DATETIME,
  INACTIVATED_BY           VARCHAR(255),
  MODIFIED_DATE            DATETIME,
  MODIFIED_BY              VARCHAR(255)
)
ENGINE=InnoDB;
