DROP TABLE IF EXISTS `SIP_JOB`;
CREATE TABLE `SIP_JOB`
(
  JOB_ID BIGINT  NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci,
  JOB_NAME  VARCHAR(50),
  START_TIME DATETIME,
  END_TIME DATETIME,
  JOB_STATUS VARCHAR(50),
  TOTAL_FILES_COUNT BIGINT NOT NULL,
  SUCCESS_FILES_COUNT BIGINT NOT NULL,
  FILE_PATTERN VARCHAR(255),
  JOB_TYPE VARCHAR(50) NOT NULL,
  CREATED_DATE  DATETIME NULL,
  CREATED_BY   VARCHAR(255),
  UPDATED_DATE DATETIME,
  UPDATED_BY   VARCHAR(255),
  CONSTRAINT SIP_JOB_PK PRIMARY KEY (JOB_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;