#!/bin/bash
awk "(\$1 == \"${1:-:}:\"){print \$2; exit;}" $0; exit
#
name:    sip-rtps
version: 0
release: 0
#
user:    mapr
group:   mapr
#
optdir:  /opt/bda/sip-rtps
#vardir:  /var/opt/bda/sip-rtps
#
# more values can be added on the box 
# TBD: rpm.host - installation host
#
