DROP TABLE IF EXISTS RESET_PWD_DTLS ;

CREATE TABLE RESET_PWD_DTLS 
(
  RESET_PWD_DTLS_SYS_ID BIGINT NOT NULL,
  USER_ID VARCHAR(255) DEFAULT NULL,
  RANDOM_HASHCODE VARCHAR(255) DEFAULT NULL,
  CREATED_TIME BIGINT DEFAULT NULL,
  VALID_UPTO BIGINT DEFAULT NULL,
  CREATED_DATE DATETIME DEFAULT NULL,
  VALID SMALLINT DEFAULT NULL,
  INACTIVATED_DATE DATETIME DEFAULT NULL
) ENGINE=InnoDB;
