DROP TABLE IF EXISTS CONFIG_VAL;

CREATE TABLE CONFIG_VAL
(
  CONFIG_VAL_SYS_ID     BIGINT  NOT NULL,
  CONFIG_VAL_CODE      	VARCHAR(100)  NOT NULL,
  CONFIG_VAL_DESC     	VARCHAR(255)  NOT NULL,
  CONFIG_VAL_OBJ_TYPE	  VARCHAR(100) NOT NULL,
  CONFIG_VAL_OBJ_GROUP  VARCHAR(100) NOT NULL,
  ACTIVE_STATUS_IND     TINYINT NOT NULL,
  CREATED_DATE    			DATETIME NOT NULL,
  CREATED_BY       			VARCHAR(255)NOT NULL,
  INACTIVATED_DATE   	  DATETIME,
  INACTIVATED_BY        VARCHAR(255),
  MODIFIED_DATE     		DATETIME,
  MODIFIED_BY        		VARCHAR(255)
)ENGINE=InnoDB COMMENT='Purpose : CONFIG_VAL table provides feature for additional configurable properties for the SAW';
