DROP TABLE IF EXISTS MODULE_PRIVILEGES;
Create Table MODULE_PRIVILEGES
(
	MODULE_PRIV_SYS_ID	BIGINT  NOT NULL,
	MODULE_SYS_ID 	BIGINT  NOT NULL,
	PRIVILEGE_CODES_SYS_ID BIGINT NOT NULL

)ENGINE=InnoDB COMMENT='Purpose : MODULE_PRIVILEGES table provides a list of privileges for every module in the system';
