info:
  component: Synchronoss scheduler Service
spring:
  application:
    name: saw-sechduler-service
  #mariaDB (metadata) DB details
  datasource:
    url: jdbc:mariadb://localhost:3306/saw_logs
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
    max-active: 25
    testOnBorrow: true
    testOnConnect: true
    testOnReturn: true
    validationQuery: SELECT 1
    testWhileIdle: true
    logValidationErrors: true
    jpa:
      properties:
        hibernate:
           dialect:org.hibernate.dialect.MariaDB53Dialect

server:
  address: localhost
  port: 9600
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

saw-analysis-service-url: http://localhost:9200/analysis
saw-dispatch-service-url: http://localhost:9400/exports
       
