DROP TABLE IF EXISTS ANALYSIS;

CREATE TABLE ANALYSIS
(
  ANALYSIS_SYS_ID BIGINT  NOT NULL,
  CUST_PROD_MOD_FEATURE_SYS_ID	  BIGINT NOT NULL,
  ANALYSIS_ID	  BIGINT NOT NULL,
  ANALYSIS_NAME     VARCHAR(100) NOT NULL,
  ACTIVE_STATUS_IND    TINYINT NOT NULL,
  CREATED_DATE     DATETIME NOT NULL,
  CREATED_BY       VARCHAR(255) NOT NULL,
  INACTIVATED_DATE   DATETIME,
  INACTIVATED_BY     VARCHAR(255),
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY        VARCHAR(255)
)ENGINE=InnoDB;