CREATE TABLE `sec_group_dsk_attribute` (
  `SEC_GROUP_DSK_ATTRIBUTE_SYS_ID` BIGINT(20) NOT NULL ,
  `SEC_GROUP_SYS_ID` BIGINT(20) NOT NULL,
  `ATTRIBUTE_NAME` VARCHAR(100) NOT NULL
  )
  ENGINE=InnoDB
