DROP TABLE IF EXISTS SEC_GROUP_DSK_ATTRIBUTE ;

CREATE TABLE SEC_GROUP_DSK_ATTRIBUTE (
  SEC_GROUP_DSK_ATTRIBUTE_SYS_ID BIGINT(20) NOT NULL ,
  SEC_GROUP_SYS_ID BIGINT(20) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(100) NOT NULL
  )
  ENGINE=InnoDB ;
