DROP TABLE IF EXISTS SEC_GROUP_DSK_VALUE;

CREATE TABLE SEC_GROUP_DSK_VALUE (
  SEC_GROUP_DSK_VALUE_SYS_ID BIGINT(20) NOT NULL,
  SEC_GROUP_DSK_ATTRIBUTE_SYS_ID BIGINT(20) NULL,
  DSK_VALUE VARCHAR(45) NULL
  )
  ENGINE=InnoDB ;