DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
  USER_SYS_ID        BIGINT  NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  EMAIL               VARCHAR(255) NOT NULL,
  ROLE_SYS_ID        BIGINT NOT NULL,
  CUSTOMER_SYS_ID    BIGINT NOT NULL,
  ENCRYPTED_PASSWORD VARCHAR(255) NOT NULL,
  FIRST_NAME         VARCHAR(100) NOT NULL,
  MIDDLE_NAME        VARCHAR(100),
  LAST_NAME          VARCHAR(100) NOT NULL,
  ACTIVE_STATUS_IND  TINYINT NOT NULL,
  SEC_GROUP_SYS_ID BIGINT(20) NULL,
  CREATED_DATE     DATETIME NOT NULL,
  CREATED_BY       VARCHAR(255)NOT NULL,
  INACTIVATED_DATE   DATETIME,
  INACTIVATED_BY     VARCHAR(255),
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY        VARCHAR(255),
  PWD_MODIFIED_DATE	 DATETIME
)
ENGINE=InnoDB;



