#!/bin/bash
#
# Configure MapR client for access to the development MapR cluster
#
set -eu

name="bda_lab_batch"
host="mapr02:7222"
# For SAW MapR container
#name="demo.mapr.io"
#host="${SAW_MAPR_PORT_7222_TCP_ADDR}:${SAW_MAPR_PORT_7222_TCP_PORT}"

/opt/mapr/server/configure.sh -N $name -c -C $host
