#!/bin/bash
#
# Configure MapR client for access to the development MapR cluster
#
set -eu

name="demo.mapr.io"
# Workaround: As Docker DNS lookups do not work inside CentOS 7
# containers for now, Docker links are used as a workaround.  The
# hostname and port for Docker links is provided in environment
# variables, so insert them here.
host="saw-mapr:7222"

/opt/mapr/server/configure.sh -N $name -c -C $host
