#!/bin/bash
#
# Load SAW test metrics for pivot/chart
#
set -eu

echo "Loading Elasticsearch metric"

sudo_mapr="sudo -u mapr"
hadoop_put="hadoop fs -put -f"
mdcli="/opt/saw/service/bin/mdcli.sh"
dir=$(dirname $0)

load_metric() {
    # The MapR container might still be starting up, so wait until MapR-FS
    # has been verified being available
    echo "Waiting for MapR-FS to become available"
    while ! hadoop fs -ls / > /dev/null 2>&1; do
        sleep 5
        echo "Retrying accessing MapR-FS"
    done
    # Load the semantic node
    test_sn=$1
    test_sn_output=$test_sn-output
    $sudo_mapr $hadoop_put $dir/$test_sn /
    $sudo_mapr $mdcli -i /$test_sn -o /$test_sn_output
}

load_metric test_semantic_node_es.json
$dir/saw-metrics-es-data
