#!/bin/sh
#
# Load SAW test metrics
#
# Note: To reduce startup time, this should be put into its own
# startup service that runs in parallel with saw-deploy.service.
# Block on "http://localhost/services" becoming responsive before
# proceeding.
set -eu

dir=$(dirname $0)
$dir/saw-metrics-es
$dir/saw-metrics load
