#!/bin/bash
#
# Load SAW test metrics for pivot/chart
#
set -eu

echo "Loading Elasticsearch metric data"

dir=$(dirname $0)
curl -sS -X PUT 'http://localhost:8200/test/type/1?pretty' \
     -H 'Content-Type: application/json' -d @$dir/test_es.json
