#!/bin/sh
#
# Load SAW test metrics
#
set -eu

chown -R mapr /root
sudo_mapr="sudo -u mapr"
hadoop_put="hadoop fs -put "
mdcli="/opt/saw/service/bin/mdcli.sh"

metrics=/root/saw-metrics
test_do=test_data_object.json
test_sn=test_semantic_node.json

generate_test_json() {
    local ts val
    for row in {1..1000}; do
        ts="$(date +%s)"
        echo -n "{"
        val="$(seq -s '' -w 100)"
        for col in $(seq -s ' ' -w 100); do
            echo -n "\"col_$col\": \"$val\", "
        done
        echo -n "\"ts\": \"$ts\""
        echo "}"
    done
}

generate_test_semantic_node_json() {
    cat $metrics/$test_sn.head
    for col in $(seq -s ' ' -w 100); do
        generate_semantic_node_column "col_$col"
        echo ","
    done
    generate_semantic_node_column "ts"
    cat $metrics/$test_sn.tail
}

generate_semantic_node_column() {
    local name=$1
    cat <<EOF
{
    "name": "$name",
    "columnName": "$name",
    "displayName": "$name",
    "aliasName": "",
    "table": "test",
    "type": "string",
    "joinEligible": false,
    "filterEligible": true
}
EOF
}

#
# Generate semantic node and data
#

echo "Generating semantic node and data"
generate_test_json > $metrics/test.json
generate_test_semantic_node_json > $metrics/$test_sn

#
# Put semantic node, data object and data in the data lake
#

echo "Putting semantic node and data into the datalake"
# Load the data object
test_do_output=$test_do-output
$sudo_mapr $hadoop_put $metrics/$test_do /
$sudo_mapr $mdcli -i /$test_do -o /$test_do_output
# Insert the data object ID into the semantic node
set -o pipefail
id=$(hadoop fs -cat /$test_do_output | grep TEST \
         | sed -e 's/.*".*":"\(.*\)".*/\1/')
sed -i -e "s/@DATA_OBJECT_ID@/$id/" $metrics/$test_sn
# Load the semantic node
test_sn_output=$test_sn-output
$sudo_mapr $hadoop_put $metrics/$test_sn /
$sudo_mapr $mdcli -i /$test_sn -o /$test_sn_output
# Upload the test data to the data lake
$sudo_mapr $hadoop_put $metrics/test.json /
