 INSERT INTO `MODULE_PRIVILEGES` (`MODULE_SYS_ID`,`PRIVILEGE_CODES_SYS_ID`) VALUES (
  (SELECT MODULE_SYS_ID FROM MODULES WHERE MODULE_NAME = 'ANALYZE'),
  (SELECT PRIVILEGE_CODES_SYS_ID FROM privilege_codes WHERE PRIVILEGE_CODES_NAME = 'CREATE'));
