/*******************************************************************************
 Filename:  V20__RTIS_REGISTRATION.sql
 Purpose:   To add new RTIS registration link for Workbench Module
 Date:      20-09-2018
********************************************************************************/


/*******************************************************************************
TABLE Scripts Starts
********************************************************************************/
-- Querying for appropriate ID's required to insert under Workbench module
select @l_cust_prod_mod_feature_sys_id := max(cust_prod_mod_feature_sys_id) FROM CUSTOMER_PRODUCT_MODULE_FEATURES;
Select @l_privilege_sys_id := max(privilege_sys_id) from privileges;

-- Storing rtis provision script in CUSTOMER_PRODUCT_MODULE_FEATURES and PRIVILEGES table
DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 1;
DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES where FEATURE_CODE like '%RTIS000001';
INSERT INTO CUSTOMER_PRODUCT_MODULE_FEATURES (CUST_PROD_MOD_FEATURE_SYS_ID,CUST_PROD_MOD_SYS_ID,DEFAULT_URL,FEATURE_NAME,FEATURE_DESC,FEATURE_CODE,FEATURE_TYPE,`DEFAULT`,ACTIVE_STATUS_IND,CREATED_DATE,CREATED_BY,INACTIVATED_DATE,INACTIVATED_BY,MODIFIED_DATE,MODIFIED_BY)
SELECT  @l_cust_prod_mod_feature_sys_id + 1 CUST_PROD_MOD_FEATURE_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, '/' DEFAULT_URL, 'RTIS' FEATURE_NAME, 'RTIS' FEATURE_DESC, concat('SYNCHRONOSS', 'RTIS000001') FEATURE_CODE, concat('PARENT_',concat('SYNCHRONOSS', 'RTIS000001')) FEATURE_TYPE,
0 'DEFAULT', 1 ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY, NULL INACTIVATED_DATE, NULL INACTIVATED_BY, NULL MODIFIED_DATE, NULL MODIFIED_BY;

DELETE FROM PRIVILEGES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 1;
INSERT INTO PRIVILEGES (PRIVILEGE_SYS_ID, CUST_PROD_SYS_ID,CUST_PROD_MOD_SYS_ID, CUST_PROD_MOD_FEATURE_SYS_ID, ROLE_SYS_ID, ANALYSIS_SYS_ID, PRIVILEGE_CODE, PRIVILEGE_DESC, ACTIVE_STATUS_IND, CREATED_DATE, CREATED_BY)
  SELECT @l_privilege_sys_id+1 PRIVILEGE_SYS_ID, '1' CUST_PROD_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, @l_cust_prod_mod_feature_sys_id + 1 CUST_PROD_MOD_FEATURE_SYS_ID, '1' ROLE_SYS_ID, '0' ANALYSIS_SYS_ID, '128' PRIVILEGE_CODE, 'All' PRIVILEGE_DESC, '1' ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY;

DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 2;
DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES where FEATURE_CODE like '%RtisReg001';
INSERT INTO CUSTOMER_PRODUCT_MODULE_FEATURES (CUST_PROD_MOD_FEATURE_SYS_ID,CUST_PROD_MOD_SYS_ID,DEFAULT_URL,FEATURE_NAME,FEATURE_DESC,FEATURE_CODE,FEATURE_TYPE,`DEFAULT`,ACTIVE_STATUS_IND,CREATED_DATE,CREATED_BY,INACTIVATED_DATE,INACTIVATED_BY,MODIFIED_DATE,MODIFIED_BY)
SELECT  @l_cust_prod_mod_feature_sys_id + 2 CUST_PROD_MOD_FEATURE_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, 'rtis/registration' DEFAULT_URL, 'RTIS Registration' FEATURE_NAME, 'RTIS Registration' FEATURE_DESC, concat('SYNCHRONOSS', 'RtisReg001') FEATURE_CODE, concat('CHILD_',concat('SYNCHRONOSS', 'RTIS000001')) FEATURE_TYPE,
0 'DEFAULT', 1 ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY, NULL INACTIVATED_DATE, NULL INACTIVATED_BY, NULL MODIFIED_DATE, NULL MODIFIED_BY;

DELETE FROM PRIVILEGES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 2;
INSERT INTO PRIVILEGES (PRIVILEGE_SYS_ID, CUST_PROD_SYS_ID,CUST_PROD_MOD_SYS_ID, CUST_PROD_MOD_FEATURE_SYS_ID, ROLE_SYS_ID, ANALYSIS_SYS_ID, PRIVILEGE_CODE, PRIVILEGE_DESC, ACTIVE_STATUS_IND, CREATED_DATE, CREATED_BY)
SELECT @l_privilege_sys_id+2 PRIVILEGE_SYS_ID, '1' CUST_PROD_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, @l_cust_prod_mod_feature_sys_id + 2 CUST_PROD_MOD_FEATURE_SYS_ID, '1' ROLE_SYS_ID, '0' ANALYSIS_SYS_ID,'128' PRIVILEGE_CODE, 'All' PRIVILEGE_DESC, '1' ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY;

DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 3;
DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES where FEATURE_CODE like '%RtisAppKey001';
INSERT INTO CUSTOMER_PRODUCT_MODULE_FEATURES (CUST_PROD_MOD_FEATURE_SYS_ID,CUST_PROD_MOD_SYS_ID,DEFAULT_URL,FEATURE_NAME,FEATURE_DESC,FEATURE_CODE,FEATURE_TYPE,`DEFAULT`,ACTIVE_STATUS_IND,CREATED_DATE,CREATED_BY,INACTIVATED_DATE,INACTIVATED_BY,MODIFIED_DATE,MODIFIED_BY)
SELECT  @l_cust_prod_mod_feature_sys_id + 3 CUST_PROD_MOD_FEATURE_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, 'rtis/appkeys' DEFAULT_URL, 'RTIS App Keys' FEATURE_NAME, 'RTIS App Keys' FEATURE_DESC, concat('SYNCHRONOSS', 'RtisAppKey001') FEATURE_CODE, concat('CHILD_',concat('SYNCHRONOSS', 'RTIS000001')) FEATURE_TYPE,
0 'DEFAULT', 1 ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY, NULL INACTIVATED_DATE, NULL INACTIVATED_BY, NULL MODIFIED_DATE, NULL MODIFIED_BY;

DELETE FROM PRIVILEGES WHERE CUST_PROD_MOD_FEATURE_SYS_ID = @l_cust_prod_mod_feature_sys_id + 3;
INSERT INTO PRIVILEGES (PRIVILEGE_SYS_ID, CUST_PROD_SYS_ID,CUST_PROD_MOD_SYS_ID, CUST_PROD_MOD_FEATURE_SYS_ID, ROLE_SYS_ID, ANALYSIS_SYS_ID, PRIVILEGE_CODE, PRIVILEGE_DESC, ACTIVE_STATUS_IND, CREATED_DATE, CREATED_BY)
SELECT @l_privilege_sys_id+3 PRIVILEGE_SYS_ID, '1' CUST_PROD_SYS_ID, 4 CUST_PROD_MOD_SYS_ID, @l_cust_prod_mod_feature_sys_id + 3 CUST_PROD_MOD_FEATURE_SYS_ID, '1' ROLE_SYS_ID, '0' ANALYSIS_SYS_ID,'128' PRIVILEGE_CODE, 'All' PRIVILEGE_DESC, '1' ACTIVE_STATUS_IND, now() CREATED_DATE, 'admin' CREATED_BY;

/*******************************************************************************
Inserting categories and sub-categories for Workbench module
********************************************************************************/

/*******************************************************************************
TABLE Scripts Ends
********************************************************************************/
