/*******************************************************************************
 Add default category and subcategory to Alert Module
********************************************************************************/
-- Correcting module Name
UPDATE MODULES SET MODULE_NAME='ALERTS' WHERE MODULE_NAME= 'ALERT';

SELECT @PRODUCT_SYS_ID := PRODUCT_SYS_ID from PRODUCTS WHERE PRODUCT_CODE = 'SAWD000001';
SELECT @MODULE_SYS_ID := MODULE_SYS_ID from MODULES WHERE MODULE_CODE = 'ALRT000001';
SELECT @PROD_MOD_SYS_ID := PROD_MOD_SYS_ID FROM `PRODUCT_MODULES` WHERE PRODUCT_SYS_ID = @PRODUCT_SYS_ID AND MODULE_SYS_ID = @MODULE_SYS_ID;
SELECT @CUST_PROD_MOD_SYS_ID :=CUST_PROD_MOD_SYS_ID FROM CUSTOMER_PRODUCT_MODULES WHERE PROD_MOD_SYS_ID = @PROD_MOD_SYS_ID ;



--Adding Categories and sub categories and their priviliges
INSERT INTO MODULE_PRIVILEGES (`MODULE_SYS_ID`,`PRIVILEGE_CODES_SYS_ID`) SELECT M.MODULE_SYS_ID ,PC.PRIVILEGE_CODES_SYS_ID FROM MODULES M , privilege_codes PC WHERE M.MODULE_NAME = 'ALERTS' and PC.PRIVILEGE_CODES_NAME = 'ACCESS';

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'/','Alerts','Alerts','ALERT12','PARENT_ALERT12',0,1,NOW(),'admin');
SELECT @CUSTOMER_PROD_MOD_SYS_ID_1 := CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE='ALERT12';
INSERT INTO `PRIVILEGES` (`CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES ('1', @CUSTOMER_PROD_MOD_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_1, '1', '0', '128', 'All', '1', NOW(), 'admin');

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'view','View Alerts','View Alerts','VIEWALERT','CHILD_ALERT12',0,1,NOW(),'admin');
SELECT @CUSTOMER_PROD_MOD_SYS_ID_1 := CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE='VIEWALERT';
INSERT INTO `PRIVILEGES` (`CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES ('1', @CUSTOMER_PROD_MOD_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_1, '1', '0', '32768', 'All', '1', NOW(), 'admin');

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'configure','Configure Alerts','Configure Alerts','CONFIGUREALERT','CHILD_ALERT12',0,1,NOW(),'admin');
SELECT @CUSTOMER_PROD_MOD_SYS_ID_1 := CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE='CONFIGUREALERT';
INSERT INTO `PRIVILEGES` (`CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES ('1', @CUSTOMER_PROD_MOD_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_1, '1', '0', '32768', 'All', '1', NOW(), 'admin');
