/*******************************************************************************
 Filename:  V29__ID3_ENABLED.sql
 Purpose:   Add ID3 Integration and Enabled for the users in SIP.
 Date:      26-12-2019
********************************************************************************/

/*******************************************************************************
Create Table Scripts Starts
********************************************************************************/
DROP TABLE IF EXISTS ID3_CLIENT_DETAILS;

CREATE TABLE ID3_CLIENT_DETAILS
(
    ID3_CLIENT_SYS_ID bigint(20) NOT NULL COMMENT 'ID3_CLIENT_SYS_ID refers to the unique Id autogenerated',
    ID3_CLIENT_ID     bigint(20) NOT NULL COMMENT 'ID3_CLIENT_ID refers to the ID3 to which the client will belong to which Domain',
    ID3_CLIENT_SECRET varchar(100) NOT NULL COMMENT 'ID3_CLIENT_SECRET refers to the secret key in ID3 for which these client added',
    ID3_DOMAIN_NAME   varchar(100) NOT NULL COMMENT 'ID3_DOMAIN_NAME gives the details of the ID3 DOMAIN NAME',
    ACTIVE_STATUS_IND tinyint(4) NOT NULL COMMENT 'ACTIVE_STATUS_IND indicates CLIENT is active',
    CREATED_TIME      datetime NOT NULL COMMENT 'CREATED_TIME specifies the time at which the entry is created',
    CREATED_BY        varchar(255) NOT NULL COMMENT 'CREATED_BY specifies the user who created this entry',
    MODIFIED_TIME     datetime COMMENT 'MODIFIED_TIME indicates the time at which the entry was modified',
    MODIFIED_BY       varchar(255) COMMENT 'MODIFIED_BY indicates the time at which the entry was modified'
) ENGINE = InnoDB COMMENT='PURPOSE: ID3_CLIENT_DETAILS is used to hold the list of ID3 clients details';

DROP TABLE IF EXISTS ID3_TICKET_DETAILS;
CREATE TABLE ID3_TICKET_DETAILS
(
    ID3_TICKET_DETAILS_SYS_ID bigint(20) NOT NULL COMMENT 'ID3_TICKET_DETAILS_SYS_ID refers to the unique Id autogenerated',
    ID3_CLIENT_SYS_ID         bigint(20) NOT NULL COMMENT 'ID3_CLIENT_SYS_ID refers to the unique Id from ID3_CLIENT_DETAILS table',
    SIP_TICKET_ID             bigint(20) NOT NULL COMMENT 'ID3_TICKET_ID refers to the unique Id from ID3_CLIENT_DETAILS table',
    VALID_INDICATOR           tinyint(4) NOT NULL COMMENT 'VALID_INDICATOR indicates authorization ticket is valid',
    CREATED_TIME              datetime NOT NULL COMMENT 'CREATED_TIME specifies the time at which the entry is created',
    CREATED_BY                varchar(255) NOT NULL COMMENT 'CREATED_BY specifies the user who created this entry',
    MODIFIED_TIME             datetime COMMENT 'MODIFIED_TIME indicates the time at which the entry was modified',
    MODIFIED_BY               varchar(255) COMMENT 'MODIFIED_BY indicates the time at which the entry was modified'
) ENGINE = InnoDB COMMENT='PURPOSE: ID3_TICKET_DETAILS is used to hold the ID3 clients authorization details';

/*******************************************************************************
 Create Table Scripts Starts
********************************************************************************/


ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS ID3_ENABLED BOOLEAN AFTER `ACTIVE_STATUS_IND`;

/*******************************************************************************
 ALTER Table Scripts Ends
********************************************************************************/


/*******************************************************************************
 TABLE Scripts Ends
********************************************************************************/
