/*******************************************************************************
 Filename:  V8__WB_CAT_UPDATES.sql
 Purpose:   To add new categories and subcategories for Workbench Module
 Date:      11-14-2018
********************************************************************************/


/*******************************************************************************
TABLE Scripts Starts
********************************************************************************/
-- Querying for appropriate ID's required to insert under Workbench module

SELECT @CUSTOMER_SYS_ID := CUSTOMER_SYS_ID FROM CUSTOMERS WHERE CUSTOMER_CODE = 'SYNCHRONOSS';
SELECT @PRODUCT_SYS_ID := PRODUCT_SYS_ID from PRODUCTS WHERE PRODUCT_CODE = 'SAWD000001';
SELECT @MODULE_SYS_ID := MODULE_SYS_ID from MODULES WHERE MODULE_CODE = 'WRK000001';
SELECT @PROD_MOD_SYS_ID := PROD_MOD_SYS_ID FROM `PRODUCT_MODULES` WHERE PRODUCT_SYS_ID = @PRODUCT_SYS_ID AND MODULE_SYS_ID = @MODULE_SYS_ID;
SELECT @CUST_PROD_MOD_SYS_ID := CUST_PROD_MOD_SYS_ID FROM CUSTOMER_PRODUCT_MODULES WHERE CUSTOMER_SYS_ID = @CUSTOMER_SYS_ID AND PROD_MOD_SYS_ID = @PROD_MOD_SYS_ID;

-- Storing generic privilege insert statement in variable which can be used to execute later after every category/sub-category insertion
SET @PRIVILEGE_DESC = 'ALL';
SET @CREATED_BY = 'admin';
SET @PRIV_INS_STMT = 'INSERT INTO `PRIVILEGES` (`CUST_PROD_SYS_ID`, `CUST_PROD_MOD_SYS_ID`, `CUST_PROD_MOD_FEATURE_SYS_ID`, `ROLE_SYS_ID`, `ANALYSIS_SYS_ID`, `PRIVILEGE_CODE`, `PRIVILEGE_DESC`, `ACTIVE_STATUS_IND`, `CREATED_DATE`, `CREATED_BY`) VALUES 
(1, @CUST_PROD_MOD_SYS_ID, @CUST_PROD_MOD_FEATURE_SYS_ID, 1, 0, 128, @PRIVILEGE_DESC, 1, NOW(), @CREATED_BY);';
PREPARE stmt FROM @PRIV_INS_STMT;

/*******************************************************************************
Inserting categories and sub-categories for Workbench module
********************************************************************************/

-- Inserting category/sub-category
INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'/','Datasets','Datasets Management','DSM0000001','PARENT_DSM0000001',0,1,NOW(),'admin');

-- Inserting respective priviliges for above inserted category/sub-category
SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;


INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'dataobjects','View Datasets','View Datasets','VIEWDATASETS001','CHILD_DSM0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'dataset/add','Add Dataset','Add Datasets','ADDDATASETS001','CHILD_DSM0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'/','Datapods','Datapods Management','DPM0000001','PARENT_DPM0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'semantic/create','Create Datapod','Create Datapod','CREATEDATAPOD001','CHILD_DPM0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'semantic/update','Update Datapod','Update Datapod','UPDATEDATAPOD001','CHILD_DPM0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'/','Data Ingestion Service','Data Ingestion Service','DIS0000001','PARENT_DIS0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;

INSERT INTO `CUSTOMER_PRODUCT_MODULE_FEATURES` (`CUST_PROD_MOD_SYS_ID`,`DEFAULT_URL`,`FEATURE_NAME`,`FEATURE_DESC`,`FEATURE_CODE`,`FEATURE_TYPE`,`DEFAULT`,`ACTIVE_STATUS_IND`,`CREATED_DATE`,`CREATED_BY`) VALUES (@CUST_PROD_MOD_SYS_ID,'datasource/create','Channel Management','Channel Management','CHANNELMANAGE001','CHILD_DIS0000001',0,1,NOW(),'admin');

SELECT @CUST_PROD_MOD_FEATURE_SYS_ID := LAST_INSERT_ID();
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Delete previously inserted category and sub-category which are not needed anymore
SELECT @CUST_PROD_MOD_FEATURE_SYS_ID_1 := CUST_PROD_MOD_FEATURE_SYS_ID from CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE = 'WORKBENCH52';
SELECT @CUST_PROD_MOD_FEATURE_SYS_ID_2 := CUST_PROD_MOD_FEATURE_SYS_ID from CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE = 'MYWORKBENCH52';
DELETE FROM CUSTOMER_PRODUCT_MODULE_FEATURES WHERE FEATURE_CODE IN ('WORKBENCH52', 'MYWORKBENCH52');
DELETE FROM PRIVILEGES WHERE CUST_PROD_MOD_FEATURE_SYS_ID IN (@CUST_PROD_MOD_FEATURE_SYS_ID_1, @CUST_PROD_MOD_FEATURE_SYS_ID_2);

/*******************************************************************************
TABLE Scripts Ends
********************************************************************************/

