info:
  component: Synchronoss Gateway Service
spring:
  application:
    name: saw-gateway-service
server:
  address: localhost
  port: 9100 
  context-path: ''
  compression:
    enabled: true    

analysis:
    service:
        host: https://saw.bda.poc.velocity-va.synchronoss.net/api
metadata:
    service:
        host: https://saw.bda.poc.velocity-va.synchronoss.net/api
semantic:
    service:
        host: https://saw.bda.poc.velocity-va.synchronoss.net/api
security:
    service:
        host: http://localhost:9000/saw-security
export:
    service:
        host: http://localhost:9400       


api:
    gateway:
        endpoints:
        -   location: ${metadata.service.host}
            method: POST
            path: '[/]md*'
        -   location: ${analysis.service.host}
            method: GET
            path: '[/]analysis*'
        -   location: ${analysis.service.host}
            method: POST
            path: '[/]analysis*'
        -   location: ${semantic.service.host}
            method: POST
            path: '[/]semantic*'          
        -   location: ${export.service.host}
            method : GET
            path : '[/]export.*'
        
        
        