info:
  component: Synchronoss Gateway Service
spring:
  application:
    name: saw-gateway-service
  http:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
  main:
    banner-mode: 'off'
server:
  address: localhost
  port: 9100
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json



analysis:
    service:
        host: http://localhost:9300
internal-analysis:
    service:
        host: http://localhost:9200
metadata:
    service:
        host: http://localhost:9200
semantic:
    service:
        host: http://localhost:9200
security:
    service:
        host: http://localhost:9000
export:
    service:
        host: http://localhost:9400
observe:
    service:
        host: http://localhost:9500
scheduler:
    service:
        host: http://localhost:9600
workbench:
    service:
        host: http://localhost:9700

api:
  gateway:
        endpoints:
        -   location: ${metadata.service.host}
            method: POST
            path: '[/]md*'
        -   location: ${internal-analysis.service.host}
            method: GET
            path: '[/]analysis.*'
        -   location: ${internal-analysis.service.host}
            method: POST
            path: '[/]analysis*'
        -   location: ${semantic.service.host}
            method: POST
            path: '[/]semantic*'
        -   location: ${analysis.service.host}
            method: GET
            path: '/api/analyses.*'
        -   location: ${export.service.host}
            method: GET
            path: '[/]export.*'
            method : GET
            path : '[/]export.*'
        -   location: ${export.service.host}
            method : POST
            path : '[/]export.*'
        -   location: ${scheduler.service.host}
            method : GET
            path : '[/]scheduler.*'
        -   location: ${scheduler.service.host}
            method : POST
            path : '[/]scheduler.*'
        -   location: ${scheduler.service.host}
            method : DELETE
            path : '[/]scheduler.*'
        -   location: ${observe.service.host}
            method: POST
            path: '[/]observe.*'
        -   location: ${observe.service.host}
            method: GET
            path: '[/]observe.*'
        -   location: ${observe.service.host}
            method: PUT
            path: '[/]observe.*'
        -   location: ${observe.service.host}
            method: DELETE
            path: '[/]observe.*'
        -   location: ${internal-analysis.service.host}
            method: POST
            path: '[/]filters.*'
        -   location: ${workbench.service.host}
            method: POST
            path: '[/]internal/workbench.*'
        -   location: ${workbench.service.host}
            method: GET
            path: '[/]internal/workbench.*'