spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
server:
  port: 8888
  
management:
  security:
    enabled: false 

security:
  user:
    name: user
    password: password