
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
server:
  port: 8888
  
management:
  security:
    enabled: false 

security:
  user:
    name: user
    password: password

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
