#!/bin/sh
#
# Copy SAW modules into bundle project for development purposes.
# Assumes all repositories ("saw", "saw-security", "saw-serviecs" and
# "saw-web") are checked out at the same level.  To be removed when
# all SAW Git repositories are merged.
#
set -eu

root=$(dirname $0)/..
repos=$root/..

cd $root

t="clean package -DskipTests"
mvn_security() {
    mvn -f $repos/saw-security/pom.xml $t
    rm -f ext/saw-security-*.tgz
    cp $repos/saw-security/target/saw-security-*.tgz ext
}
mvn_services() {
    mvn -f $repos/saw-services/pom.xml -pl dist -am $t
    rm -f ext/saw-services-*.tgz
    cp $repos/saw-services/dist/target/saw-services-*.tgz ext
}
mvn_web() {
    mvn -f $repos/saw-web/pom.xml $t -Prpm
    rm -f ext/saw-web-*.tgz
    cp $repos/saw-web/target/saw-web-*.tgz ext
}

modules="${1:-security services web}"
for module in $modules; do
    echo "+ build $module"
    (cd $repos/saw-$module && .mvn/update-revision)
    mvn_$module
    (cd $repos/saw-$module && git checkout .mvn/maven.config)
done

ext/prepare
