#!/bin/sh
#
# Build and copy SAW module packages into bundle project
#
set -eu

root=$(dirname $0)/..
repos=.
cd $root

mvn="mvn"
bamboo_mvn="/opt/apache-maven-3.5.0/bin/mvn"
if [ -f "$bamboo_mvn" ]; then
    mvn="$bamboo_mvn"
fi

t="clean package"
mvn_security() {
    $mvn -f $repos/saw-security/pom.xml $t
    rm -f ext/saw-security-*.tgz
    cp $repos/saw-security/target/saw-security-*.tgz ext
}
mvn_services() {
    $mvn -f $repos/saw-services/pom.xml -pl dist -am $t
    rm -f ext/saw-services-*.tgz
    cp $repos/saw-services/dist/target/saw-services-*.tgz ext
}
mvn_web() {
    $mvn -f $repos/saw-web/pom.xml $t -Prpm
    rm -f ext/saw-web-*.tgz
    cp $repos/saw-web/target/saw-web-*.tgz ext
}

modules="${1:-security services web}"
for module in $modules; do
    echo "+ build $module"
    repo=$repos/saw-$module
    if [ ! -d $repo ]; then
        echo "Error: Expected repository at $repo, but directory not found"
        exit 1
    fi
    (cd $repo && .mvn/update-revision)
    mvn_$module
    (cd $repo && git checkout .mvn/maven.config)
done
