#!/bin/sh
#
# Prepare SAW module packages for inclusion into the SAW bundle
# release package.  To be removed when all SAW modules are build from
# the same Maven multi-module project.
#
set -eu

dir=$(dirname $0)
cd $dir

# Prepare SAW module packages from merged repositories
./prepare-dev $@

# Add SAW modules
rm -rf modules
mkdir modules
cd modules
for module in saw-security saw-services saw-web; do
    tar -xzf ../$module-*.tgz
    ln -s $module-* $module
done
