#!/bin/sh
#
# Update the revision property in ".mvn/maven.config".  Populates the
# parameterized Maven POM "version" property with a value calculated
# from the current Git revision.  Used in continuous integration to
# build packages that are automatically versioned.
#
set -euo pipefail

dir=$(dirname $0)
revision=$(git describe --match 'v*' | sed -e 's/^v//')
revision_nodash=$(echo $revision | sed -e 's/-/_/g')
maven_config="-Drevision=$revision -Drevision.nodash=$revision_nodash"
echo "$maven_config" > $dir/maven.config
