- name: check to see if sip_mariadb_dare_key.enc path exists
  stat: path=/etc/my.cnf.d/sip_mariadb_dare_key.enc
  register: path_sip_mariadb_dare_key

- name: fail when sip_mariadb_dare_key is not defined
  fail: msg="sip_mariadb_dare_key must be specified and cannot be blank"
  when: sip_mariadb_dare_key is not defined or sip_mariadb_dare_key == ''

- name: fail when sip_mariadb_dare_key_password is not defined
  fail: msg="sip_mariadb_dare_key_password must be specified and cannot be blank"
  when: sip_mariadb_dare_key_password is not defined or sip_mariadb_dare_key_password == ''  

#encrypt the sip_mariadb_dare_key using openssl enc
- name: encrypt sip_mariadb_dare_key
  shell: echo "{{ sip_mariadb_dare_key }}" | openssl enc -aes-256-cbc -md sha1 -k "{{ sip_mariadb_dare_key_password }}" -out /etc/my.cnf.d/sip_mariadb_dare_key.enc
  when: not path_sip_mariadb_dare_key.stat.exists
  no_log: true

- name: Copy the dare configuration file to /etc/my.cnf.d/
  template: 
    src: sip-mariadb-dare.cnf.j2
    dest: /etc/my.cnf.d/sip-mariadb-dare.cnf
  notify:
    - restart mariadb
  
    







