info:
  component: Synchronoss Observe Service
spring:
  application:
    name: saw-export-service
server:
  address: localhost
  port: 9500
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
metastore:
    base:  hdfs:///main
    
  

       
