import * as split from 'lodash/split';
import * as memoize from 'lodash/memoize';
import * as fpPipe from 'lodash/fp/pipe';
import * as fpToPairs from 'lodash/fp/toPairs';
import * as fpMap from 'lodash/fp/map';
import * as fpSortBy from 'lodash/fp/sortBy';
// tslint:disable

function obj2Array(mapDataIndex) {
  return fpPipe(
    fpToPairs,
    fpMap(([name, groupObj]) => ({
      name,
      children: fpPipe(
        fpToPairs,
        fpMap(([name, path]) => ({name, path})),
        fpSortBy('name')
        )(groupObj)
    }))
  )(mapDataIndex)
}

function getByGeoType(mapDataIndex) {

  return geoType => {
    const [type] = split(geoType, ':');
    switch (type) {
    case 'country':
      return obj2Array(mapDataIndex['Custom']);
    case 'state':
      return [{
        name: "Countries",
        children: [{
          name: "United States of America",
          path: "countries/us/us-all.geo.json"
        }]
      }];
    case 'county':
      return obj2Array(mapDataIndex['USA States']);
    case 'zip':
      return [];
    }
  }
}

const index = {
  "Custom": {
    "Africa": "custom/africa.geo.json",
    "Antarctica": "custom/antarctica.geo.json",
    "Asia": "custom/asia.geo.json",
    "Benelux": "custom/benelux.geo.json",
    "British Isles": "custom/british-isles.geo.json",
    "Canada and United States of America": "custom/usa-and-canada.geo.json",
    "Central America": "custom/central-america.geo.json",
    "Europe": "custom/europe.geo.json",
    "European Union": "custom/european-union.geo.json",
    "Middle East": "custom/middle-east.geo.json",
    "Nordic Countries": "custom/nordic-countries.geo.json",
    "North America without central": "custom/north-america-no-central.geo.json",
    "North America": "custom/north-america.geo.json",
    "North Atlantic Treaty Organization": "custom/nato.geo.json",
    "Oceania": "custom/oceania.geo.json",
    "Scandinavia": "custom/scandinavia.geo.json",
    "South America": "custom/south-america.geo.json",
    "World continents": "custom/world-continents.geo.json"
  },
  "Countries": {
    "Afghanistan": "countries/af/af-all.geo.json",
    "Albania": "countries/al/al-all.geo.json",
    "Algeria": "countries/dz/dz-all.geo.json",
    "American Samoa": "countries/as/as-all.geo.json",
    "Andorra": "countries/ad/ad-all.geo.json",
    "Angola": "countries/ao/ao-all.geo.json",
    "Antigua and Barbuda": "countries/ag/ag-all.geo.json",
    "Argentina": "countries/ar/ar-all.geo.json",
    "Armenia": "countries/am/am-all.geo.json",
    "Australia": "countries/au/au-all.geo.json",
    "Austria": "countries/at/at-all.geo.json",
    "Azerbaijan": "countries/az/az-all.geo.json",
    "Bahrain": "countries/bh/bh-all.geo.json",
    "Bangladesh": "countries/bd/bd-all.geo.json",
    "Barbados": "countries/bb/bb-all.geo.json",
    "Belarus": "countries/by/by-all.geo.json",
    "Belgium": "countries/be/be-all.geo.json",
    "Belize": "countries/bz/bz-all.geo.json",
    "Benin": "countries/bj/bj-all.geo.json",
    "Bhutan": "countries/bt/bt-all.geo.json",
    "Bolivia": "countries/bo/bo-all.geo.json",
    "Bosnia and Herzegovina": "countries/ba/ba-all.geo.json",
    "Botswana": "countries/bw/bw-all.geo.json",
    "Brazil": "countries/br/br-all.geo.json",
    "Brunei": "countries/bn/bn-all.geo.json",
    "Bulgaria": "countries/bg/bg-all.geo.json",
    "Burkina Faso": "countries/bf/bf-all.geo.json",
    "Burundi": "countries/bi/bi-all.geo.json",
    "Cambodia": "countries/kh/kh-all.geo.json",
    "Cameroon": "countries/cm/cm-all.geo.json",
    "Canada": "countries/ca/ca-all.geo.json",
    "Canada, admin2": "countries/ca/ca-all-all.geo.json",
    "Cape Verde": "countries/cv/cv-all.geo.json",
    "Central African Republic": "countries/cf/cf-all.geo.json",
    "Chad": "countries/td/td-all.geo.json",
    "Chile": "countries/cl/cl-all.geo.json",
    "China with Hong Kong and Macau": "countries/cn/custom/cn-all-sar.geo.json",
    "China with Hong Kong, Macau, and Taiwan": "countries/cn/custom/cn-all-sar-taiwan.geo.json",
    "China": "countries/cn/cn-all.geo.json",
    "Colombia": "countries/co/co-all.geo.json",
    "Comoros": "countries/km/km-all.geo.json",
    "Cook Islands": "countries/ck/ck-all.geo.json",
    "Costa Rica": "countries/cr/cr-all.geo.json",
    "Croatia": "countries/hr/hr-all.geo.json",
    "Cuba": "countries/cu/cu-all.geo.json",
    "Cyprus": "countries/cy/cy-all.geo.json",
    "Czech Republic": "countries/cz/cz-all.geo.json",
    "Democratic Republic of the Congo": "countries/cd/cd-all.geo.json",
    "Denmark": "countries/dk/dk-all.geo.json",
    "Djibouti": "countries/dj/dj-all.geo.json",
    "Dominica": "countries/dm/dm-all.geo.json",
    "Dominican Republic": "countries/do/do-all.geo.json",
    "East Timor": "countries/tl/tl-all.geo.json",
    "Ecuador": "countries/ec/ec-all.geo.json",
    "Egypt": "countries/eg/eg-all.geo.json",
    "El Salvador": "countries/sv/sv-all.geo.json",
    "Equatorial Guinea": "countries/gq/gq-all.geo.json",
    "Eritrea": "countries/er/er-all.geo.json",
    "Estonia": "countries/ee/ee-all.geo.json",
    "Ethiopia": "countries/et/et-all.geo.json",
    "Faroe Islands": "countries/fo/fo-all.geo.json",
    "Fiji": "countries/fj/fj-all.geo.json",
    "Finland": "countries/fi/fi-all.geo.json",
    "France": "countries/fr/fr-all.geo.json",
    "France, admin2": "countries/fr/fr-all-all.geo.json",
    "France, mainland admin2": "countries/fr/custom/fr-all-all-mainland.geo.json",
    "France, mainland": "countries/fr/custom/fr-all-mainland.geo.json",
    "French Southern and Antarctic Lands": "countries/tf/tf-all.geo.json",
    "Gabon": "countries/ga/ga-all.geo.json",
    "Gambia": "countries/gm/gm-all.geo.json",
    "Georgia": "countries/ge/ge-all.geo.json",
    "Germany": "countries/de/de-all.geo.json",
    "Germany, admin2": "countries/de/de-all-all.geo.json",
    "Ghana": "countries/gh/gh-all.geo.json",
    "Greece": "countries/gr/gr-all.geo.json",
    "Greenland": "countries/gl/gl-all.geo.json",
    "Grenada": "countries/gd/gd-all.geo.json",
    "Guam": "countries/gu/gu-all.geo.json",
    "Guatemala": "countries/gt/gt-all.geo.json",
    "Guinea Bissau": "countries/gw/gw-all.geo.json",
    "Guinea": "countries/gn/gn-all.geo.json",
    "Guyana": "countries/gy/gy-all.geo.json",
    "Haiti": "countries/ht/ht-all.geo.json",
    "Honduras": "countries/hn/hn-all.geo.json",
    "Hungary": "countries/hu/hu-all.geo.json",
    "Iceland": "countries/is/is-all.geo.json",
    "India with Andaman and Nicobar": "countries/in/custom/in-all-andaman-and-nicobar.geo.json",
    "India with disputed territories": "countries/in/custom/in-all-disputed.geo.json",
    "India": "countries/in/in-all.geo.json",
    "Indonesia": "countries/id/id-all.geo.json",
    "Iran": "countries/ir/ir-all.geo.json",
    "Iraq": "countries/iq/iq-all.geo.json",
    "Ireland": "countries/ie/ie-all.geo.json",
    "Israel": "countries/il/il-all.geo.json",
    "Italy": "countries/it/it-all.geo.json",
    "Ivory Coast": "countries/ci/ci-all.geo.json",
    "Jamaica": "countries/jm/jm-all.geo.json",
    "Japan": "countries/jp/jp-all.geo.json",
    "Jordan": "countries/jo/jo-all.geo.json",
    "Kazakhstan": "countries/kz/kz-all.geo.json",
    "Kenya": "countries/ke/ke-all.geo.json",
    "Kosovo": "countries/kv/kv-all.geo.json",
    "Kuwait": "countries/kw/kw-all.geo.json",
    "Kyrgyzstan": "countries/kg/kg-all.geo.json",
    "Laos": "countries/la/la-all.geo.json",
    "Latvia": "countries/lv/lv-all.geo.json",
    "Lebanon": "countries/lb/lb-all.geo.json",
    "Lesotho": "countries/ls/ls-all.geo.json",
    "Liberia": "countries/lr/lr-all.geo.json",
    "Libya": "countries/ly/ly-all.geo.json",
    "Liechtenstein": "countries/li/li-all.geo.json",
    "Lithuania": "countries/lt/lt-all.geo.json",
    "Luxembourg": "countries/lu/lu-all.geo.json",
    "Macedonia": "countries/mk/mk-all.geo.json",
    "Madagascar": "countries/mg/mg-all.geo.json",
    "Malawi": "countries/mw/mw-all.geo.json",
    "Malaysia": "countries/my/my-all.geo.json",
    "Mali": "countries/ml/ml-all.geo.json",
    "Malta": "countries/mt/mt-all.geo.json",
    "Mauritania": "countries/mr/mr-all.geo.json",
    "Mauritius": "countries/mu/mu-all.geo.json",
    "Mexico": "countries/mx/mx-all.geo.json",
    "Moldova": "countries/md/md-all.geo.json",
    "Monaco": "countries/mc/mc-all.geo.json",
    "Mongolia": "countries/mn/mn-all.geo.json",
    "Montenegro": "countries/me/me-all.geo.json",
    "Morocco": "countries/ma/ma-all.geo.json",
    "Mozambique": "countries/mz/mz-all.geo.json",
    "Myanmar": "countries/mm/mm-all.geo.json",
    "Namibia": "countries/na/na-all.geo.json",
    "Nauru": "countries/nr/nr-all.geo.json",
    "Nepal": "countries/np/np-all.geo.json",
    "New Caledonia": "countries/nc/nc-all.geo.json",
    "New Zealand": "countries/nz/nz-all.geo.json",
    "Nicaragua": "countries/ni/ni-all.geo.json",
    "Niger": "countries/ne/ne-all.geo.json",
    "Nigeria": "countries/ng/ng-all.geo.json",
    "North Korea": "countries/kp/kp-all.geo.json",
    "Northern Mariana Islands": "countries/mp/mp-all.geo.json",
    "Norway with Svalbard and Jan Mayen": "countries/no/custom/no-all-svalbard-and-jan-mayen.geo.json",
    "Norway": "countries/no/no-all.geo.json",
    "Norway, admin2": "countries/no/no-all-all.geo.json",
    "Oman": "countries/om/om-all.geo.json",
    "Pakistan": "countries/pk/pk-all.geo.json",
    "Palau": "countries/pw/pw-all.geo.json",
    "Panama": "countries/pa/pa-all.geo.json",
    "Papua New Guinea": "countries/pg/pg-all.geo.json",
    "Paraguay": "countries/py/py-all.geo.json",
    "Peru": "countries/pe/pe-all.geo.json",
    "Philippines": "countries/ph/ph-all.geo.json",
    "Poland": "countries/pl/pl-all.geo.json",
    "Portugal": "countries/pt/pt-all.geo.json",
    "Puerto Rico": "countries/pr/pr-all.geo.json",
    "Qatar": "countries/qa/qa-all.geo.json",
    "Republic of Serbia": "countries/rs/rs-all.geo.json",
    "Republic of the Congo": "countries/cg/cg-all.geo.json",
    "Romania": "countries/ro/ro-all.geo.json",
    "Russia with disputed territories": "countries/ru/custom/ru-all-disputed.geo.json",
    "Russia": "countries/ru/ru-all.geo.json",
    "Rwanda": "countries/rw/rw-all.geo.json",
    "Saint Kitts and Nevis": "countries/kn/kn-all.geo.json",
    "Saint Lucia": "countries/lc/lc-all.geo.json",
    "Saint Vincent and the Grenadines": "countries/vc/vc-all.geo.json",
    "Samoa": "countries/ws/ws-all.geo.json",
    "San Marino": "countries/sm/sm-all.geo.json",
    "Sao Tome and Principe": "countries/st/st-all.geo.json",
    "Saudi Arabia": "countries/sa/sa-all.geo.json",
    "Senegal": "countries/sn/sn-all.geo.json",
    "Seychelles": "countries/sc/sc-all.geo.json",
    "Sierra Leone": "countries/sl/sl-all.geo.json",
    "Singapore": "countries/sg/sg-all.geo.json",
    "Slovakia": "countries/sk/sk-all.geo.json",
    "Slovenia": "countries/si/si-all.geo.json",
    "Solomon Islands": "countries/sb/sb-all.geo.json",
    "Somalia": "countries/so/so-all.geo.json",
    "Somaliland": "countries/sx/sx-all.geo.json",
    "South Africa": "countries/za/za-all.geo.json",
    "South Korea": "countries/kr/kr-all.geo.json",
    "South Sudan": "countries/ss/ss-all.geo.json",
    "Spain": "countries/es/es-all.geo.json",
    "Sri Lanka": "countries/lk/lk-all.geo.json",
    "Sudan": "countries/sd/sd-all.geo.json",
    "Suriname": "countries/sr/sr-all.geo.json",
    "Swaziland": "countries/sz/sz-all.geo.json",
    "Sweden": "countries/se/se-all.geo.json",
    "Switzerland": "countries/ch/ch-all.geo.json",
    "Syria": "countries/sy/sy-all.geo.json",
    "Taiwan": "countries/tw/tw-all.geo.json",
    "Tajikistan": "countries/tj/tj-all.geo.json",
    "Thailand": "countries/th/th-all.geo.json",
    "The Bahamas": "countries/bs/bs-all.geo.json",
    "The Netherlands": "countries/nl/nl-all.geo.json",
    "The Netherlands, admin2": "countries/nl/nl-all-all.geo.json",
    "Togo": "countries/tg/tg-all.geo.json",
    "Trinidad and Tobago": "countries/tt/tt-all.geo.json",
    "Tunisia": "countries/tn/tn-all.geo.json",
    "Turkey": "countries/tr/tr-all.geo.json",
    "Turkmenistan": "countries/tm/tm-all.geo.json",
    "Uganda": "countries/ug/ug-all.geo.json",
    "Ukraine": "countries/ua/ua-all.geo.json",
    "United Arab Emirates": "countries/ae/ae-all.geo.json",
    "United Kingdom countries": "countries/gb/custom/gb-countries.geo.json",
    "United Kingdom": "countries/gb/gb-all.geo.json",
    "United Republic of Tanzania": "countries/tz/tz-all.geo.json",
    "United States Virgin Islands": "countries/vi/vi-all.geo.json",
    "United States of America with Territories": "countries/us/custom/us-all-territories.geo.json",
    "United States of America": "countries/us/us-all.geo.json",
    "United States of America, admin2": "countries/us/us-all-all.geo.json",
    "United States of America, admin2, highres": "countries/us/us-all-all-highres.geo.json",
    "United States of America, congressional districts (113th)": "countries/us/custom/us-113-congress.geo.json",
    "United States of America, mainland": "countries/us/custom/us-all-mainland.geo.json",
    "United States of America, small": "countries/us/custom/us-small.geo.json",
    "Uruguay": "countries/uy/uy-all.geo.json",
    "Uzbekistan": "countries/uz/uz-all.geo.json",
    "Vanuatu": "countries/vu/vu-all.geo.json",
    "Venezuela": "countries/ve/ve-all.geo.json",
    "Vietnam": "countries/vn/vn-all.geo.json",
    "Wallis and Futuna": "countries/wf/wf-all.geo.json",
    "Western Sahara": "countries/eh/eh-all.geo.json",
    "Yemen": "countries/ye/ye-all.geo.json",
    "Zambia": "countries/zm/zm-all.geo.json",
    "Zimbabwe": "countries/zw/zw-all.geo.json"
  },
  "USA States": {
    "Alabama, admin2": "countries/us/us-al-all.geo.json",
    "Alaska, admin2": "countries/us/us-ak-all.geo.json",
    "Arizona, admin2": "countries/us/us-az-all.geo.json",
    "Arkansas, admin2": "countries/us/us-ar-all.geo.json",
    "California, admin2": "countries/us/us-ca-all.geo.json",
    "Colorado, admin2": "countries/us/us-co-all.geo.json",
    "Connecticut, admin2": "countries/us/us-ct-all.geo.json",
    "Delaware, admin2": "countries/us/us-de-all.geo.json",
    "District of Columbia, admin2": "countries/us/us-dc-all.geo.json",
    "Florida, admin2": "countries/us/us-fl-all.geo.json",
    "Georgia, admin2": "countries/us/us-ga-all.geo.json",
    "Hawaii, admin2": "countries/us/us-hi-all.geo.json",
    "Idaho, admin2": "countries/us/us-id-all.geo.json",
    "Illinois, admin2": "countries/us/us-il-all.geo.json",
    "Indiana, admin2": "countries/us/us-in-all.geo.json",
    "Iowa, admin2": "countries/us/us-ia-all.geo.json",
    "Kansas, admin2": "countries/us/us-ks-all.geo.json",
    "Kentucky, admin2": "countries/us/us-ky-all.geo.json",
    "Louisiana, admin2": "countries/us/us-la-all.geo.json",
    "Maine, admin2": "countries/us/us-me-all.geo.json",
    "Maryland, admin2": "countries/us/us-md-all.geo.json",
    "Massachusetts, admin2": "countries/us/us-ma-all.geo.json",
    "Michigan, admin2": "countries/us/us-mi-all.geo.json",
    "Minnesota, admin2": "countries/us/us-mn-all.geo.json",
    "Mississippi, admin2": "countries/us/us-ms-all.geo.json",
    "Missouri, admin2": "countries/us/us-mo-all.geo.json",
    "Montana, admin2": "countries/us/us-mt-all.geo.json",
    "Nebraska, admin2": "countries/us/us-ne-all.geo.json",
    "Nevada, admin2": "countries/us/us-nv-all.geo.json",
    "New Hampshire, admin2": "countries/us/us-nh-all.geo.json",
    "New Jersey, admin2": "countries/us/us-nj-all.geo.json",
    "New Mexico, admin2": "countries/us/us-nm-all.geo.json",
    "New York, admin2": "countries/us/us-ny-all.geo.json",
    "North Carolina, admin2": "countries/us/us-nc-all.geo.json",
    "North Dakota, admin2": "countries/us/us-nd-all.geo.json",
    "Ohio, admin2": "countries/us/us-oh-all.geo.json",
    "Oklahoma, admin2": "countries/us/us-ok-all.geo.json",
    "Oregon, admin2": "countries/us/us-or-all.geo.json",
    "Pennsylvania, admin2": "countries/us/us-pa-all.geo.json",
    "Rhode Island, admin2": "countries/us/us-ri-all.geo.json",
    "South Carolina, admin2": "countries/us/us-sc-all.geo.json",
    "South Dakota, admin2": "countries/us/us-sd-all.geo.json",
    "Tennessee, admin2": "countries/us/us-tn-all.geo.json",
    "Texas, admin2": "countries/us/us-tx-all.geo.json",
    "Utah, admin2": "countries/us/us-ut-all.geo.json",
    "Vermont, admin2": "countries/us/us-vt-all.geo.json",
    "Virginia, admin2": "countries/us/us-va-all.geo.json",
    "Washington, admin2": "countries/us/us-wa-all.geo.json",
    "West Virginia, admin2": "countries/us/us-wv-all.geo.json",
    "Wisconsin, admin2": "countries/us/us-wi-all.geo.json",
    "Wyoming, admin2": "countries/us/us-wy-all.geo.json"
  }
};

const getMapDataIndexByGeoType = memoize(getByGeoType(index));
export {
  getMapDataIndexByGeoType
};
