#!/usr/bin/env bash

# Get app_home (with version number)
source /tmp/.saw-service.tmp.env || exit
: ${app_home:?no value}
( cd ${app_home} ) || exit

mkdir -m 755 -p /etc/saw

chown -R mapr:mapr ${app_home}
chmod 750 ${app_home}/sbin ${app_home}/conf ${app_home}/lib
chmod 755 ${app_home} ${app_home}/var ${app_home}/var/log ${app_home}/var/run

( cd /opt/saw; rm -f service; ln -s $(basename ${app_home}) service )

service_env=${app_home}/conf/service.env

{
    echo "SAW_HOME=/opt/saw"
    echo "SAW_SERVICE_HOME=/opt/saw/service"
    echo "SAW_SERVICE_PORT=9100"
    echo "declare -r SAW_SERVICE_USER=saw-user"
    echo "declare -r SAW_SERVICE_CURRENT_HOME=${app_home}"
} >$service_env

chown mapr:mapr $service_env
chmod 750 $service_env

rm -f /etc/saw/service.env
ln -s $service_env /etc/saw/

rm -f /tmp/.saw-service.tmp.env

echo "Add emails in ~service-user/.forward to get notifications from service_runner.sh"
grep -q 'service_runner' /etc/rc.local || {
    echo "Add line to /etc/rc.local:"
    echo '/opt/saw/service/sbin/service_runner.sh &>/tmp/rc.local.service_runner.log'
}
echo
echo "SAW Services postinstall step completed"
