#!/usr/bin/env bash

source /etc/saw/service.env || exit

echo "Remove link on current version of XDF Transport Server"

rm -rf ${SAW_HOME}/service/var/log/*
rm -f ${SAW_HOME}/service
rm -f /etc/saw/service.env


echo "XDF Transport Server pre-remove step has been completed"
