#!/usr/bin/env bash

source /etc/saw/service.env || exit

echo "Remove link on current version of SAW Common Service"

rm -rf /var/saw/service/log/*
rm -f ${SAW_HOME}/service
rm -f /etc/saw/service.env


echo "SAW Common Service pre-remove step has been completed"
