#!/bin/bash
#
# Initialize MapR container
#
set -eux

# For Spark shell, run at boot time when MapR-FS available
#hadoop fs -mkdir /apps/spark

# Start rsyslog to persist system logs
/etc/init.d/rsyslog start

# Start Spark slaves
/opt/mapr/spark/spark-current/sbin/start-slaves.sh

# Workaround: Using "/usr/sbin/lsof -i :7222" or similar as
# healthcheck indicates success too early, as the MapR image
# /usr/bin/init-script restarts services once, so hook into the init
# script instead
touch /saw-mapr-init-done
