// For more configuration please refer to https://zefoy.github.io/ngx-color-picker/
export const DEFAULT_COLOR_PICKER_OPTION = {
  bgColor: '',
  position: 'top-right',
  width: '180px',
  height: 'auto',
  display: 'popup',
  mode: 'color',
  labelText: 'Color :',
  presetColorLabel: '',
  okButton: false,
  okButtonClass: '',
  oKButtonText: '',
  alphaChannel: 'hex6',
  cancelButton: false,
  cancelButtonClass: '',
  cancelButtonText: '',
  ignoreHTMLElements: [],
  presetColors: [],
  positionOffset: '10%',
  positionRelativeToArrow: true,
  toggle: false,
  saveOnClickOutside: true,
  relativeToArrow: true
};
