server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
      wait-time-in-ms-when-sync-empty: 0
      
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

management:
  security:
    enabled: false 
    