- hosts: saw-services
  # Workaround: Until IPA is set up on saw03 in Velocity Labs, disable
  # "become" as it results in a sudo error
  #become: true
  vars:
    title: SAW Transport Service
    module: saw-transport-service
    rpm: "{{module}}-1.0.0-1.noarch.rpm"
    target_rpm: ../{{module}}/target/rpm/{{module}}/RPMS/noarch/{{rpm}}
    tmp_rpm: /root/{{rpm}}
  tasks:
    - name: Copy SAW Transport Service package
      synchronize: src="{{target_rpm}}" dest="{{tmp_rpm}}"
    - name: Install SAW Transport Service package
      yum: name={{tmp_rpm}} state=present
- hosts: saw-services
  # Workaround: Until IPA is set up on saw03 in Velocity Labs, disable
  # "become" as it results in a sudo error
  #become: true
  vars:
    title: SAW Scheduler Service
    module: saw-scheduler-service
    rpm: "{{module}}-1.0.0-1-noarch.rpm"
    target_rpm: ../{{module}}/target/{{rpm}}
    tmp_rpm: /root/{{rpm}}
  tasks:
    - name: Copy SAW Scheduler Service package
      synchronize: src="{{target_rpm}}" dest="{{tmp_rpm}}"
    - name: Install SAW Scheduler Service package
      yum: name={{tmp_rpm}} state=present
