- hosts: saw-security
  become: true
  tasks:
    - name: Install MariaDB package
      yum: name=mariadb-server state=present
    - name: Enable and start MariaDB service
      systemd: name=mariadb enabled=true state=started
