- hosts: saw-services
  become: true
  vars:
    title: SAW Scheduler Service
    module: saw-scheduler-service
    jar: /opt/{{module}}/{{module}}.jar
  tasks:
    # Workaround: Copy plain files until the module has RPM packaging
    - name: Prepare {{title}} directory
      file: path=/opt/{{module}} state=directory
    # Add the service main file
    - name: Install {{title}}
      copy:
        src: ../{{module}}/target/{{module}}-1.0.0-exec.jar
        dest: "{{jar}}"
    # Add daily launcher
    - name: Install {{title}} daily launcher
      copy:
        content: "sudo -u mapr java -jar {{jar}} 2>&1 | logger -t {{module}}\n"
        dest: "/etc/cron.daily/{{module}}-daily"
        mode: a+x
