ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_SYS_ID); 
ALTER TABLE PRODUCTS CHANGE PRODUCT_SYS_ID PRODUCT_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE PRODUCTS AUTO_INCREMENT = 1;

ALTER TABLE MODULES ADD CONSTRAINT MODULES_PK PRIMARY KEY (MODULE_SYS_ID); 
ALTER TABLE MODULES CHANGE MODULE_SYS_ID MODULE_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE MODULES AUTO_INCREMENT = 1;

ALTER TABLE PRODUCT_MODULES ADD CONSTRAINT PRODUCT_MODULES_PK PRIMARY KEY (PROD_MOD_SYS_ID); 
ALTER TABLE PRODUCT_MODULES CHANGE PROD_MOD_SYS_ID PROD_MOD_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE PRODUCT_MODULES AUTO_INCREMENT = 1;
ALTER TABLE PRODUCT_MODULES ADD CONSTRAINT PRODUCT_MODULE_FK_1 FOREIGN KEY (PRODUCT_SYS_ID) REFERENCES PRODUCTS(PRODUCT_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PRODUCT_MODULES ADD CONSTRAINT PRODUCT_MODULE_FK_2 FOREIGN KEY (MODULE_SYS_ID) REFERENCES MODULES(MODULE_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_SYS_ID); 
ALTER TABLE CUSTOMERS CHANGE CUSTOMER_SYS_ID CUSTOMER_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE CUSTOMERS AUTO_INCREMENT = 1;

ALTER TABLE CUSTOMER_PRODUCTS ADD CONSTRAINT CUSTOMER_PRODUCTS_PK PRIMARY KEY (CUST_PROD_SYS_ID); 
ALTER TABLE CUSTOMER_PRODUCTS CHANGE CUST_PROD_SYS_ID CUST_PROD_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE CUSTOMER_PRODUCTS AUTO_INCREMENT = 1;
ALTER TABLE CUSTOMER_PRODUCTS ADD CONSTRAINT CUSTOMER_PRODUCTS_FK_1 FOREIGN KEY (CUSTOMER_SYS_ID) REFERENCES CUSTOMERS(CUSTOMER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CUSTOMER_PRODUCTS ADD CONSTRAINT CUSTOMER_PRODUCTS_FK_2 FOREIGN KEY (PRODUCT_SYS_ID) REFERENCES PRODUCTS(PRODUCT_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CUSTOMER_PRODUCT_MODULES ADD CONSTRAINT CUSTOMER_PRODUCT_MODULES_PK PRIMARY KEY (CUST_PROD_MOD_SYS_ID); 
ALTER TABLE CUSTOMER_PRODUCT_MODULES CHANGE CUST_PROD_MOD_SYS_ID CUST_PROD_MOD_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE CUSTOMER_PRODUCT_MODULES AUTO_INCREMENT = 1;
ALTER TABLE CUSTOMER_PRODUCT_MODULES ADD CONSTRAINT CUSTOMER_PRODUCT_MODULES_FK_2 FOREIGN KEY (PROD_MOD_SYS_ID) REFERENCES PRODUCT_MODULES(PROD_MOD_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CUSTOMER_PRODUCT_MODULES ADD CONSTRAINT CUSTOMER_PRODUCT_MODULES_FK_3 FOREIGN KEY (CUSTOMER_SYS_ID) REFERENCES CUSTOMERS(CUSTOMER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CUSTOMER_PRODUCT_MODULE_FEATURES ADD CONSTRAINT CUST_PROD_MOD_FEATURE_SYS_ID PRIMARY KEY (CUST_PROD_MOD_FEATURE_SYS_ID); 
ALTER TABLE CUSTOMER_PRODUCT_MODULE_FEATURES CHANGE CUST_PROD_MOD_FEATURE_SYS_ID CUST_PROD_MOD_FEATURE_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE CUSTOMER_PRODUCT_MODULE_FEATURES AUTO_INCREMENT = 1;
ALTER TABLE CUSTOMER_PRODUCT_MODULE_FEATURES ADD CONSTRAINT CUSTOMER_PRODUCT_MODULE_FEATURES_FK_1 FOREIGN KEY (CUST_PROD_MOD_SYS_ID) REFERENCES CUSTOMER_PRODUCT_MODULES(CUST_PROD_MOD_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ROLES ADD CONSTRAINT ROLE_SYS_ID_PK PRIMARY KEY (ROLE_SYS_ID); 
ALTER TABLE ROLES CHANGE ROLE_SYS_ID ROLE_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE ROLES AUTO_INCREMENT = 1;
ALTER TABLE ROLES ADD CONSTRAINT ROLES_FK_1 FOREIGN KEY (CUSTOMER_SYS_ID) REFERENCES CUSTOMERS(CUSTOMER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PRIVILEGES` ADD CONSTRAINT PRIVILEGES_PK PRIMARY KEY (PRIVILEGE_SYS_ID); 
ALTER TABLE `PRIVILEGES` CHANGE PRIVILEGE_SYS_ID PRIVILEGE_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE `PRIVILEGES` AUTO_INCREMENT = 1;
ALTER TABLE `PRIVILEGES` ADD CONSTRAINT PRIVILEGES_FK_1 FOREIGN KEY (CUST_PROD_MOD_FEATURE_SYS_ID) REFERENCES CUSTOMER_PRODUCT_MODULE_FEATURES(CUST_PROD_MOD_FEATURE_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ROLE_PRIVILEGES ADD CONSTRAINT ROLE_PRIVILEGES_PK PRIMARY KEY (ROLE_PRIVILEGES_SYS_ID); 
ALTER TABLE ROLE_PRIVILEGES CHANGE ROLE_PRIVILEGES_SYS_ID ROLE_PRIVILEGES_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE ROLE_PRIVILEGES AUTO_INCREMENT = 1;
ALTER TABLE ROLE_PRIVILEGES ADD CONSTRAINT ROLE_PRIVILEGES_FK_1 FOREIGN KEY (ROLE_SYS_ID) REFERENCES ROLES(ROLE_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ROLE_PRIVILEGES ADD CONSTRAINT ROLE_PRIVILEGES_FK_2 FOREIGN KEY (PRIVILEGE_SYS_ID) REFERENCES `PRIVILEGES`(PRIVILEGE_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (USER_SYS_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_UK  UNIQUE (USER_ID);
ALTER TABLE USERS CHANGE USER_SYS_ID USER_SYS_ID BIGINT AUTO_INCREMENT;
ALTER TABLE USERS AUTO_INCREMENT = 1;
ALTER TABLE USERS ADD CONSTRAINT USERS_FK_1 FOREIGN KEY (CUSTOMER_SYS_ID) REFERENCES CUSTOMERS(CUSTOMER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT USERS_FK_2 FOREIGN KEY (ROLE_SYS_ID) REFERENCES ROLES(ROLE_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONTACT_INFO ADD CONSTRAINT CONTACT_INFO_PK PRIMARY KEY (CONTACT_INFO_SYS_ID);
ALTER TABLE CONTACT_INFO CHANGE CONTACT_INFO_SYS_ID CONTACT_INFO_SYS_ID BIGINT AUTO_INCREMENT;
ALTER TABLE CONTACT_INFO AUTO_INCREMENT = 1;
ALTER TABLE CONTACT_INFO ADD CONSTRAINT CONTACT_INFO_FK_1 FOREIGN KEY (CUSTOMER_SYS_ID) REFERENCES CUSTOMERS(CUSTOMER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USER_CONTACT  ADD CONSTRAINT USER_CONTACT_PK   PRIMARY KEY (USER_CONTACT_SYS_ID);
ALTER TABLE USER_CONTACT CHANGE USER_CONTACT_SYS_ID USER_CONTACT_SYS_ID BIGINT AUTO_INCREMENT;
ALTER TABLE USER_CONTACT AUTO_INCREMENT = 1;
ALTER TABLE USER_CONTACT ADD CONSTRAINT USER_CONTACT_FK_1 FOREIGN KEY (USER_SYS_ID) REFERENCES USERS(USER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE USER_CONTACT ADD CONSTRAINT USER_CONTACT_FK_2 FOREIGN KEY (CONTACT_INFO_SYS_ID) REFERENCES CONTACT_INFO(CONTACT_INFO_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PASSWORD_HISTORY ADD CONSTRAINT PASSWORD_HISTORY_PK  PRIMARY KEY (PASSWORD_HISTORY_SYS_ID);
ALTER TABLE PASSWORD_HISTORY CHANGE PASSWORD_HISTORY_SYS_ID PASSWORD_HISTORY_SYS_ID BIGINT AUTO_INCREMENT;
ALTER TABLE PASSWORD_HISTORY AUTO_INCREMENT = 1;
ALTER TABLE PASSWORD_HISTORY ADD CONSTRAINT PASSWORD_HISTORY_FK_1 FOREIGN KEY (USER_SYS_ID) REFERENCES USERS(USER_SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESET_PWD_DTLS ADD CONSTRAINT RESET_PWD_DTLS_PK PRIMARY KEY (RESET_PWD_DTLS_SYS_ID); 
ALTER TABLE RESET_PWD_DTLS CHANGE RESET_PWD_DTLS_SYS_ID RESET_PWD_DTLS_SYS_ID BIGINT AUTO_INCREMENT NOT NULL;
ALTER TABLE RESET_PWD_DTLS AUTO_INCREMENT = 1;