DROP TABLE IF EXISTS `SIP_JOB`;
DROP TABLE IF EXISTS `SIP_BIS_TRANSFER`;

CREATE TABLE `BIS_JOB`
(
  JOB_ID BIGINT  NOT NULL AUTO_INCREMENT COLLATE utf8_unicode_ci,
  JOB_NAME  VARCHAR(50),
  BIS_CHANNEL_SYS_ID BIGINT,
  BIS_ROUTE_SYS_ID BIGINT,
  START_TIME DATETIME,
  END_TIME DATETIME,
  JOB_STATUS VARCHAR(50),
  TOTAL_FILES_COUNT BIGINT NOT NULL,
  SUCCESS_FILES_COUNT BIGINT NOT NULL,
  FILE_PATTERN VARCHAR(255),
  CHANNEL_TYPE VARCHAR(50) NOT NULL,
  CREATED_DATE  DATETIME NULL,
  CREATED_BY   VARCHAR(255),
  UPDATED_DATE DATETIME,
  UPDATED_BY   VARCHAR(255),
  CONSTRAINT SIP_JOB_PK PRIMARY KEY (JOB_ID)
)ENGINE=InnoDB;

INSERT INTO BIS_JOB (JOB_ID, JOB_NAME, JOB_STATUS, TOTAL_FILES_COUNT, SUCCESS_FILES_COUNT, CHANNEL_TYPE ) VALUES (-1, 'SAMPLE', 'SUCCESS', 100 ,100 , 'SFTP');

ALTER TABLE SIP_BIS.BIS_FILE_LOGS ADD COLUMN JOB_ID BIGINT NOT NULL DEFAULT -1, ADD CONSTRAINT SIP_BIS_FILE_LOGS_FK FOREIGN KEY (JOB_ID) REFERENCES BIS_JOB(JOB_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SIP_BIS.BIS_FILE_LOGS ADD COLUMN STATE_REASON TEXT;



