info:
  component: Synchronoss Storage Proxy Service
spring:
  application:
    name: saw-storage-proxy-service
server:
  address: localhost
  port: 9600
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
schema:
   file: /Users/Shared/WORK/saw/saw-services/saw-proxy-service/src/main/resources/schema/proxy-scehma.json 
elastic-search:
           cluster-name: SNCR-VELBDA-elasticsearch 
           transport-hosts: elasticsearch01.bda.poc.velocity-va.sncrcorp.net
           transport-ports: 9200   
elastic-xpack :
          cluster-active: true
          clsuter-username: elastic
          cluster-password: xuw3dUraHapret  