info:
  component: Synchronoss Storage Proxy Service
spring:
  application:
    name: saw-storage-proxy-service
logging:
  level:
    com.synchronoss.saw.storage.proxy: trace
server:
  address: localhost
  port: 9800
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
schema:
   file: /Users/spau0004/code/SIP/saw-services/saw-proxy-service/src/main/resources/schema/proxy-schema.json
elastic-search:
           cluster-name: sip-rd-es
           transport-hosts: es-rd601.ana.dev.vaste.sncrcorp.net
           transport-ports: 9200
elastic-xpack :
          cluster-active: false
          cluster-username: elastic
          cluster-password: xuw3dUraHapret
metastore:
    base:  hdfs:///main/        
         
