DROP TABLE IF EXISTS `SIP_BIS_TRANSFER`;
CREATE TABLE `SIP_BIS_TRANSFER`
(
  TRANSFER_ID BIGINT  NOT NULL AUTO_INCREMENT,
  JOB_ID BIGINT NOT NULL,
  FILE_NAME VARCHAR(50),
  FILE_PATH  VARCHAR(255),
  START_TIME DATETIME,
  END_TIME DATETIME,
  DURATION BIGINT,
  STATUS VARCHAR(50),
  FILE_PATTERN VARCHAR(255),
  TARGET_FILE_PATH VARCHAR(255),
  CREATED_TIME DATETIME,
  UPDATED_TIME DATETIME,
  STATE_REASON TEXT,
  CONSTRAINT SIP_BIS_TRANSFER_PK PRIMARY KEY (TRANSFER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;