DROP TABLE IF EXISTS `BIS_ROUTE`;
DROP TABLE IF EXISTS `BIS_CHANNEL`;
DROP TABLE IF EXISTS `BIS_FILE_LOGS`;

CREATE TABLE `BIS_CHANNEL`
(
  BIS_CHANNEL_SYS_ID BIGINT  NOT NULL AUTO_INCREMENT,
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY       VARCHAR(255),
  CREATED_DATE      DATETIME NULL,
  CREATED_BY        VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
  PRODUCT_CODE      VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
  CHANNEL_TYPE      VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
  PROJECT_CODE      VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
  CUSTOMER_CODE     VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
  STATUS            BOOLEAN DEFAULT TRUE,
  CHANNEL_METADATA  JSON NOT NULL,
  CHECK (JSON_VALID(CHANNEL_METADATA)),
  CONSTRAINT CHANNEL_PK PRIMARY KEY (BIS_CHANNEL_SYS_ID)
)ENGINE=InnoDB;

CREATE TABLE `BIS_ROUTE`
(
  BIS_ROUTE_SYS_ID BIGINT  NOT NULL AUTO_INCREMENT,
  BIS_CHANNEL_SYS_ID BIGINT NOT NULL,
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY       VARCHAR(255) COLLATE utf8_unicode_ci,
  CREATED_DATE      DATETIME NULL,
  CREATED_BY        VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
  ROUTE_METADATA    JSON NOT NULL,
  CHECK (JSON_VALID(ROUTE_METADATA)),
  CONSTRAINT ROUTE_PK PRIMARY KEY (BIS_ROUTE_SYS_ID)
) ENGINE=InnoDB;

CREATE TABLE `BIS_FILE_LOGS`
(
BIS_PID	TEXT,
BIS_ROUTE_SYS_ID	BIGINT  NOT NULL,
BIS_CHANNEL_SYS_ID BIGINT NOT NULL,
BIS_CHANNEL_TYPE  VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
BIS_FILE_PATTERN	TEXT COLLATE utf8_unicode_ci,
BIS_FILE_NAME	TEXT COLLATE utf8_unicode_ci,
BIS_ACTUAL_FILE_RCV_DATE	DATETIME NOT NULL,
BIS_RECD_FILE_NAME	TEXT COLLATE utf8_unicode_ci,
BIS_RECD_FILE_SIZE_BYTES	BIGINT UNSIGNED NOT NULL,
BIS_FILE_VALID_STATUS	VARCHAR(255) COLLATE utf8_unicode_ci,
CREATED_DATE	DATETIME NOT NULL,
MODIFIED_DATE	DATETIME NULL,
BIS_PROCESS_STATE TEXT COLLATE utf8_unicode_ci
)ENGINE=InnoDB;
