ALTER TABLE SIP_BIS.BIS_FILE_LOGS ADD COLUMN  BIS_TRANSFER_START_TIME DATETIME NULL;
ALTER TABLE SIP_BIS.BIS_FILE_LOGS ADD COLUMN  BIS_TRANSFER_END_TIME DATETIME NULL;
ALTER TABLE SIP_BIS.BIS_FILE_LOGS ADD COLUMN  BIS_TRANSFER_DURATION DATETIME NULL;