info:
  component: SIP metadata Service
spring:
  application:
    name: sip-metadata-service
  http:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
logging:
  level:
    com.synchronoss.saw.semantic: INFO
    org.springframework: INFO
    sncr.bda: INFO
server:
  address: localhost
  port: 9502
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000

metastore:
  base:  hdfs:///user/pman0003/
  analysis: analysisMetadata
semantic:
  workbench-url:  http://localhost:9700
  transport-metadata-url:  http://localhost:9200
  binary-migration-requires: false
  migration-metadata-home: /var/sip/

analysis:
  get-analysis-url:  http://localhost:9200
  binary-migration-required: false
