- name: check to see if sip_mariadb_dare_key.enc path exists
  stat: path=/etc/my.cnf.d/sip_mariadb_dare_key.enc
  register: path_sip_mariadb_dare_key

- name: generate dare key
  shell: "openssl rand -hex 32 | sed '1s/^/1;/'"
  register: sip_mariadb_dare_key
  run_once: true
  delegate_to: "{{groups['saw-security'][0]}}"
  when: not path_sip_mariadb_dare_key.stat.exists

- name: generate mariabd dare key password
  command: openssl rand -base64 16
  register: sip_mariadb_dare_key_password
  run_once: true
  delegate_to: "{{groups['saw-security'][0]}}"
  when: not path_sip_mariadb_dare_key.stat.exists

- name: keep dare key in a file
  local_action: "copy content={{ sip_mariadb_dare_key.stdout }}  dest={{ inventory_dir + '/sip_mariadb_dare_key' }}"
  run_once: true
  delegate_to: "{{groups['saw-security'][0]}}"
  when: sip_mariadb_dare_key_password.changed

- name: keep dare key password in a file
  local_action: "copy content={{ sip_mariadb_dare_key_password.stdout }}  dest={{ inventory_dir + '/sip_mariadb_dare_key_password' }}"
  run_once: true
  delegate_to: "{{groups['saw-security'][0]}}"
  when: sip_mariadb_dare_key_password.changed

- name: Look up dare key from inventory_dir file
  set_fact:
    sip_mariadb_dare_keyfile: >-
      {{ lookup('file', inventory_dir+'/sip_mariadb_dare_key') }}

- name: Look up dare key password from inventory_dir file
  set_fact:
    sip_mariadb_dare_key_passwordfile: >-
      {{ lookup('file', inventory_dir+'/sip_mariadb_dare_key_password') }}

- name: register sip_mariadb_dare_keys
  shell: echo "{{ sip_mariadb_dare_keyfile }}"
  register: reg_sip_mariadb_dare_key

- name: register sip_mariadb_dare_password
  shell: echo "{{ sip_mariadb_dare_key_passwordfile }}"
  register: reg_sip_mariadb_dare_key_password

# encrypt the sip_mariadb_dare_key using openssl enc
- name: encrypt sip_mariadb_dare_key
  shell: echo "{{ reg_sip_mariadb_dare_key.stdout }}" | openssl enc -aes-256-cbc -md sha1 -k "{{ reg_sip_mariadb_dare_key_password.stdout }}" -out /etc/my.cnf.d/sip_mariadb_dare_key.enc
  when: not path_sip_mariadb_dare_key.stat.exists
  register: encrpt_sip_mariadb_dare_key

- name: Copy the dare configuration file to /etc/my.cnf.d/
  template:
    src: sip-mariadb-dare.cnf.j2
    dest: /etc/my.cnf.d/sip-mariadb-dare.cnf
  notify:
    - restart mariadb
  when: encrpt_sip_mariadb_dare_key.changed
  
