export {
  FLOAT_TYPES,
  DEFAULT_PRECISION,
  DATE_TYPES,
  NUMBER_TYPES,
  CHART_TYPES_OBJ
} from '../../consts';

export enum DesignerStates {
  WAITING_FOR_COLUMNS,
  NO_SELECTION,
  SELECTION_WAITING_FOR_DATA,
  SELECTION_WITH_NO_DATA,
  SELECTION_WITH_DATA,
  SELECTION_OUT_OF_SYNCH_WITH_DATA
}
