CREATE SCHEMA IF NOT EXISTS SIP_BATCH_INGESTION;

DROP TABLE IF EXISTS `BIS_FILE_LOGS`;
CREATE TABLE `BIS_FILE_LOGS`
(
BIS_PID	TEXT,
BIS_ROUTE_SYS_ID	BIGINT  NOT NULL,
BIS_CHANNEL_SYS_ID BIGINT NOT NULL,
BIS_CHANNEL_TYPE  VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
BIS_FILE_PATTERN	TEXT COLLATE utf8_unicode_ci,
BIS_FILE_NAME	TEXT COLLATE utf8_unicode_ci,
BIS_ACTUAL_FILE_RCV_DATE	DATETIME NOT NULL,
BIS_RECD_FILE_NAME	TEXT COLLATE utf8_unicode_ci,
BIS_RECD_FILE_SIZE_BYTES	DOUBLE(12,4),
BIS_FILE_VALID_STATUS	VARCHAR(255) COLLATE utf8_unicode_ci,
CREATED_DATE	DATETIME NOT NULL,
MODIFIED_DATE	DATETIME NOT NULL,
BIS_PROCESS_STATE TEXT COLLATE utf8_unicode_ci
)ENGINE=InnoDB;



INSERT INTO `BIS_FILE_LOGS` (MFL_PID, BIS_ROUTE_SYS_ID, BIS_CHANNEL_SYS_ID,  BIS_CHANNEL_TYPE, BIS_FILE_PATTERN, BIS_FILE_NAME, BIS_ACTUAL_FILE_RCV_DATE, BIS_RECD_FILE_NAME, BIS_RECD_FILE_SIZE_BYTES, BIS_FILE_VALID_STATUS, CREATED_DATE, MODIFIED_DATE, BIS_PROCESS_STATE  ) VALUES (2,1,1,"TEST","TEST","TEST",NOW(),"TEST",1.0,"TEST",NOW(),NOW(),"TEST");
