#!/bin/bash
#
# Load sample Elasticsearch metric (for pivot/chart)
#
set -eu

dir=$(dirname $0)

# Load common metrics functions
. $dir/../lib/common.sh

load_semantic() {
    echo "Loading sample Elasticsearch semantic metadata"
    local datalake=$datalake_home/sample-elasticsearch
    local semantic=semantic.json
    $sudo_mapr hadoop fs -mkdir -p $datalake
    $sudo_mapr hadoop fs -put -f $dir/$semantic $datalake
    $sudo_mapr $mdcli -i $datalake/$semantic -o $datalake/$semantic-output
}

post_json() {
    curl -sS -X POST -H "Content-Type: application/json" "$@"
}

load_data() {
    local index_url="http://localhost:8200/sample"
    echo "Loading sample Elasticsearch data"
    post_json "$index_url" -d @$dir/mappings.json
    for data in $dir/data-*.json; do
        post_json "$index_url/type" -d @$data
    done
}

wait_maprfs
load_semantic
load_data
