#!/bin/bash
#
# Load sample Elasticsearch metric (for pivot/chart)
#
set -eu

dir=$(dirname $0)

# Load common metrics functions
. $dir/../lib/common.sh

load_semantic() {
    echo "Loading sample Elasticsearch semantic metadata"
    local datalake=$datalake_home/sample-elasticsearch
    local semantic=semantic.json
    $sudo_mapr hadoop fs -mkdir -p $datalake
    $sudo_mapr hadoop fs -put -f $dir/$semantic $datalake
    $sudo_mapr $mdcli -i $datalake/$semantic -o $datalake/$semantic-output
}

curl_json() {
    curl -sS -X $1 -H "Content-Type: application/json" $2 -d @$3
}

load_data() {
    local index_url="http://localhost:8200/sample"
    echo "Loading sample Elasticsearch data"
    curl_json PUT "$index_url" $dir/index.json
    for data in $dir/data-*.json; do
        curl_json POST "$index_url/sample" $data
    done
}

wait_maprfs
load_semantic
load_data
