

# Modeler Class Functions -------------------------------------------------



#' New Modeler Object Constructer function
new_modeler <- function(df,
                        target,
                        type,
                        name,
                        id,
                        version,
                        desc,
                        scientist,
                        dir,
                        samples,
                        models,
                        measure,
                        ...){


  checkmate::assert_character(target)
  checkmate::assert_character(type)
  checkmate::assert_character(name)
  checkmate::assert_character(id)
  checkmate::assert_character(version)
  checkmate::assert_character(desc)
  checkmate::assert_character(scientist)
  checkmate::test_path_for_output(dir)
  checkmate::assert_class(samples, "samples")
  checkmate::assert_list(models)
  checkmate::assert_list(measure)

  structure(
    list(
      type = type,
      name = name,
      id = id,
      version = version,
      desc = desc,
      scientist = scientist,
      created_on = Sys.time(),
      data = df,
      target = target,
      dir = dir,
      samples = samples,
      models = models,
      measure = measure,
      ...
    ),
    class = "modeler")
}


#' Modeler Validation function
valid_modeler <- function(x){

  if (! x$type %in% c("forecaster", "segmenter", "regresser", "classifier")) {
    stop("modeler type supplied not supported. Please use one of following: ",
         "\n* forecaster",
         "\n* segmenter",
         "\n* regresser",
         "\n* classifier")
  }

  if(! class(x$data) %in% c("data.frame", "tbl_spark")){
    stop("df input class not supported. modeler supports only data.frame and tbl_spark objects")
  }

  x
}


#' Modeler Helper Function
#'
#' Function to create a valid modeler object to support model building use
#' cases. Modeler is the base class from which the other more specific use cases
#' like forecaster, regresser, segmenter, etc... inherit form
#'
#' @param df dataframe with target variable and any potential predictors
#' @param target target variable for supervised use cases such as forecaster,
#'   regresser, and classifier
#' @param type type of use case (forecaster, regresser, classifier, and
#'   segmenter)
#' @param name optional name for use case. Default is to append target with type
#' @param id optional id string. A random id will be generated by default
#' @param version optional version string. will default to '1.0'
#' @param desc optional description of the use case.
#' @param scientist optional input for scientist building model. defaults to
#'   system user
#' @param dir optional directory path for saving reports, data and models
#' @param ... any addtional parameters
#'
#' @return modeler object
#' @export
#' @family use cases
#' @aliases modeler
modeler <- function(df,
                    target,
                    type,
                    name = NULL,
                    id = NULL,
                    version = NULL,
                    desc = NULL,
                    scientist = NULL,
                    dir = NULL,
                    ...){

  if(is.null(name)) name <- paste(target, type, sep = "-")
  if(is.null(id)) id <- sparklyr::random_string("id")
  if(is.null(version)) version <- "1.0"
  if(is.null(desc)) desc <- ""
  if(is.null(scientist)) scientist <- Sys.info()["user"]
  if(is.null(dir)) dir <- "./"
  default_samples <- add_default_samples(df)
  empty_models <- list()
  measure <- list()

  valid_modeler(
    new_modeler(
      df = df,
      target = target,
      type = type,
      name = name,
      id = id,
      version = version,
      desc = desc,
      scientist = scientist,
      dir = dir,
      samples = default_samples,
      models = empty_models,
      measure = measure,
      ...)
  )
}


#' Get Models Status
get_models_status <- function(obj, id = NULL){

  models <- obj$models
  if(! is.null(id))
    models <- models[models$id  == id]

  sapply(obj$models, function(m) m$status)
}


#' Get All Modeler Models
#'
#' Function to access all modeler models. Subsettable by either id or status
#'
#' @param obj modeler object
#' @param id vector of id strings
#' @param status model status code. accepts "created", "added", "trained", "evaluated", or "selected"
#'
#' @return list of model objects
#' @export
get_models <- function(obj, id = NULL, status = NULL) {
  checkmate::assert_class(obj, "modeler")
  checkmate::assert_character(id, null.ok = TRUE)
  checkmate::assert_choice(status,
                           choices = c("created", "added", "trained", "evaluated", "selected"),
                           null.ok = TRUE)

  models <- obj$models
  if(! is.null(id))
    models <- models[[names(models) == id]]

  if(! is.null(status))
    models <- models[sapply(models, function(m) m$status) == status]

  models
}



train_models.modeler <- function(obj, id = NULL){
  checkmate::assert_character(id, null.ok = TRUE)

  status <- get_models_status(obj)
  if(! is.null(id))
    status <- status[names(status) == id]

  added_ids <- names(status == "added")
  for(id in added_ids) {
    model <- get_models(obj, id = id)
    model$pipe <- flow(obj$data, model$pipe)
    indicies <- get_indicies(obj)
    for(index in indicies) {
      df_index <- model$pipe$output %>% dplyr::slice(index$train)
      fm <- fit_model(obj, data = df_index)
    }
  }
}



fit_model.model <- function(obj, data, ...) {
  fit(
    structure(list(id = obj$id), class = obj$class),
    method = obj$method,
    method_args = obj$method_args,
    target = obj$target,
    data = data,
    ...
  )
}


# Modeler Class Generics --------------------------------------------------



#' Train Model Generic
train_models <- function(obj, ...) {
  UseMethod("train_models")
}


#' Fit Model Generic
#' @export
fit_model <- function(obj, ...) {
  UseMethod("fit_model")
}


#' @export
fit <- function(obj, method, method_args, target, data, ...) {
  UseMethod("fit")
}


#' Evalutate Models Generic
evaluate_models <- function(obj, ...) {
  UseMethod("evaluate_models")
}

#' @export
evaluate <- function(x, ...) {
  UseMethod("evaluate", x)
}




#' Fit Args Generic
#' @export
fit_args <- function(x, ...) {
  UseMethod("fit_args", x)
}




#' @export
get_predictions <- function(x, ...) {
  UseMethod("get_predictions", x)
}


#' @export
get_fit <- function(x, ...) {
  UseMethod("get_fit", x)
}


#' @export
get_coefs <- function(x, ...) {
  UseMethod("get_coefs", x)
}


