

# Modeler Class Functions -------------------------------------------------



#' New Modeler Object Constructer function
new_modeler <- function(df,
                        target,
                        type,
                        name,
                        id,
                        version,
                        desc,
                        scientist,
                        dir,
                        samples,
                        models,
                        measure,
                        evaluate,
                        ...){


  checkmate::assert_character(target)
  checkmate::assert_character(type)
  checkmate::assert_character(name)
  checkmate::assert_character(id)
  checkmate::assert_character(version)
  checkmate::assert_character(desc)
  checkmate::assert_character(scientist)
  checkmate::test_path_for_output(dir)
  checkmate::assert_class(samples, "samples")
  checkmate::assert_list(models)
  checkmate::assert_list(measure)
  checkmate::assert_data_frame(evaluate)

  structure(
    list(
      type = type,
      name = name,
      id = id,
      version = version,
      desc = desc,
      scientist = scientist,
      created_on = Sys.time(),
      data = df,
      target = target,
      dir = dir,
      samples = samples,
      models = models,
      measure = measure,
      evaluate = evaluate,
      ...
    ),
    class = "modeler")
}


#' Modeler Validation function
valid_modeler <- function(x){

  if (! x$type %in% c("forecaster", "segmenter", "regresser", "classifier")) {
    stop("modeler type supplied not supported. Please use one of following: ",
         "\n* forecaster",
         "\n* segmenter",
         "\n* regresser",
         "\n* classifier")
  }

  if(! class(x$data) %in% c("data.frame", "tbl_spark")){
    stop("df input class not supported. modeler supports only data.frame and tbl_spark objects")
  }

  x
}


#' Modeler Helper Function
#'
#' Function to create a valid modeler object to support model building use
#' cases. Modeler is the base class from which the other more specific use cases
#' like forecaster, regresser, segmenter, etc... inherit form
#'
#' @param df dataframe with target variable and any potential predictors
#' @param target target variable for supervised use cases such as forecaster,
#'   regresser, and classifier
#' @param type type of use case (forecaster, regresser, classifier, and
#'   segmenter)
#' @param name optional name for use case. Default is to append target with type
#' @param id optional id string. A random id will be generated by default
#' @param version optional version string. will default to '1.0'
#' @param desc optional description of the use case.
#' @param scientist optional input for scientist building model. defaults to
#'   system user
#' @param dir optional directory path for saving reports, data and models
#' @param ... any addtional parameters
#'
#' @return modeler object
#' @export
#' @family use cases
#' @aliases modeler
modeler <- function(df,
                    target,
                    type,
                    name = NULL,
                    id = NULL,
                    version = NULL,
                    desc = NULL,
                    scientist = NULL,
                    dir = NULL,
                    ...){

  if(is.null(name)) name <- paste(target, type, sep = "-")
  if(is.null(id)) id <- sparklyr::random_string("id")
  if(is.null(version)) version <- "1.0"
  if(is.null(desc)) desc <- ""
  if(is.null(scientist)) scientist <- Sys.info()["user"]
  if(is.null(dir)) dir <- "./"
  default_samples <- add_default_samples(df)
  empty_models <- list()
  measure <- list()
  evaluate <- data.frame()

  valid_modeler(
    new_modeler(
      df = df,
      target = target,
      type = type,
      name = name,
      id = id,
      version = version,
      desc = desc,
      scientist = scientist,
      dir = dir,
      samples = default_samples,
      models = empty_models,
      measure = measure,
      evaluate = evaluate,
      ...)
  )
}



# Modeler Functions -------------------------------------------------------



#' Get Models Status
#'
#' Function to return modeler's model statuses
#'
#' @param obj modeler object
#' @param id one or more model id characters
#' @export
get_models_status <- function(obj, id = NULL){

  models <- obj$models
  if(! is.null(id))
    models <- models[models$id  == id]

  sapply(obj$models, function(m) m$status)
}


#' Get All Modeler Models
#'
#' Function to access all modeler models. Subsettable by either id or status
#'
#' @param obj modeler object
#' @param id one or more model id characters
#' @param status model status code. accepts "created", "added", "trained", "evaluated", or "selected"
#'
#' @return list of model objects
#' @export
get_models <- function(obj, ids = NULL, status = NULL) {
  checkmate::assert_class(obj, "modeler")
  checkmate::assert_character(ids, null.ok = TRUE)
  checkmate::assert_choice(status,
                           choices = c("created", "added", "trained", "evaluated", "selected"),
                           null.ok = TRUE)

  models <- obj$models
  if(! is.null(ids))
    models <- models[names(models) %in% ids]

  if(! is.null(status))
    models <- models[sapply(models, function(m) m$status) == status]

  models
}


#' Get Model Validation Predictions
#'
#' @param obj modeler object
#' @param ids one or more model id characters
#'
#' @export
get_validation_predictions <- function(obj, ids = NULL) {
  checkmate::assert_class(obj, "modeler")
  checkmate::assert_character(ids, null.ok = TRUE)
  models <- get_models(obj, ids = ids)

  preds <- data.frame()
  for (model in models) {
    checkmate::assert_class(model, "model")
    checkmate::assert_choice(model$status, c("trained", "evaluated", "selected"))

    for (i in seq_along(model$performance)) {
      smpl_name <- names(model$performance)[i]
      preds <- preds %>%
        dplyr::union_all(
          model$performance[[i]]$validation %>%
            dplyr::mutate(model = model$id,
                          sample = smpl_name)
        )
    }
  }

  preds
}



#' Get Model Train Fits
#'
#' @param obj modeler object
#' @param id model id character
#'
#' @export
get_train_fits <- function(obj, id) {
  checkmate::assert_class(obj, "modeler")
  checkmate::assert_character(id, null.ok = TRUE)
  model <- get_models(obj, ids = id)[[1]]
  checkmate::assert_class(model, "model")
  checkmate::assert_choice(model$status, c("trained", "evaluated", "selected"))

  preds <- data.frame()
  for (i in seq_along(model$performance)) {
    preds <- preds %>%
      rbind(model$performance[[i]]$train %>%
              dplyr::mutate(sample = names(model$performance)[i]))
  }

  preds
}


#' Get Target Data function
#'
#' Returns modeler target data. Calls get_target_df generic
#'
#' @param obj modeler object
#' @export
get_target <- function(obj) {
  checkmate::assert_class(obj, "modeler")
  get_target_df(obj$data, obj$target)
}


#' Get Model Evaluation Summary
#'
#' Returns data.frame with measure calculated on the validation samples
get_evalutions <- function(obj) {
  checkmate::assert_class(obj, "modeler")
  obj$evaluate
}


# Modeler Class Generics --------------------------------------------------



#' Train Model Generic
train_models <- function(obj, ...) {
  UseMethod("train_models")
}


#' Evalutate Models Generic
evaluate_models <- function(obj, ...) {
  UseMethod("evaluate_models")
}


#' @export
get_fit <- function(x, ...) {
  UseMethod("get_fit", x)
}


#' @export
get_coefs <- function(x, ...) {
  UseMethod("get_coefs", x)
}

#' Get Target Dataframe Generic Method
#'
#' Function to return modeler target
get_target_df <- function(obj, target) {
  UseMethod("get_target_df")
}



# Modeler Class Methods ---------------------------------------------------


#' Train Models Method for Modeler Class
train_models.modeler <- function(obj, id = NULL) {
  checkmate::assert_character(id, null.ok = TRUE)

  status <- get_models_status(obj)
  if (!is.null(id))
    status <- status[names(status) == id]

  added_ids <- names(status == "added")
  for (id in added_ids) {
    model <- get_models(obj, ids = id)[[1]]
    model$pipe <- flow(obj$data, model$pipe)
    indicies <- get_indicies(obj)
    model$performance <- indicies
    for (i in seq_along(indicies)) {
      index <- indicies[[i]]
      model <- fit(model,
                   data = model$pipe$output %>% dplyr::slice(index$train))
      fitted <- fitted(model)
      predicted <- predict(model,
                           data = model$pipe$output %>% dplyr::slice(index$train))
      perf <- list(train = data.frame("index" = index$train,
                                      fitted = fitted),
                   validation = data.frame("index" = index$validation,
                                           predicted = predicted))
      model$performance[[i]] <- perf
    }
  }
  obj
}


#' Get Target data.frame Method
#'
#'@export
get_target_df.data.frame <- function(df, target) {
 checkmate::assert_subset(target, colnames(df))
  df[, target, drop=FALSE]
}
