DROP TABLE IF EXISTS PASSWORD_HISTORY;
create table PASSWORD_HISTORY
(
  PASSWORD_HISTORY_SYS_ID VARCHAR(255) NOT NULL,
  USER_SYS_ID             BIGINT NOT NULL,
  PASSWORD                VARCHAR(255) NOT NULL,
  DATE_OF_CHANGE          DATETIME NOT NULL
)
ENGINE=InnoDB;


