DROP TABLE IF EXISTS PRIVILEGE_GROUPS;
CREATE TABLE PRIVILEGE_GROUPS (
  PRIVILEGE_GRP_SYS_ID BIGINT NOT NULL,
  PRIVILEGE_GRP_CODE VARCHAR(255) NOT NULL,
  PRIVILEGE_GRP_CODE_DESC VARCHAR(255) NOT NULL
) ENGINE=INNODB;
