DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS
(
  PRODUCT_SYS_ID      BIGINT NOT NULL ,
  PRODUCT_NAME        VARCHAR(100) NOT NULL,
  PRODUCT_CODE        VARCHAR(50) NOT NULL,
  PRODUCT_DESC         VARCHAR(500) NOT NULL,
  ACTIVE_STATUS_IND   TINYINT NOT NULL,
  CREATED_DATE     DATETIME NOT NULL,
  CREATED_BY       VARCHAR(255) NOT NULL,
  INACTIVATED_DATE   DATETIME,
  INACTIVATED_BY     VARCHAR(255),
  MODIFIED_DATE     DATETIME,
  MODIFIED_BY        VARCHAR(255)
)ENGINE=InnoDB;