#!/bin/sh
#
# Deploy SAW Security to an environment
#

error() {
    echo "Error: $*"
    exit 1
}

if ! command -v ansible-playbook > /dev/null; then
    error "Ansible not found; please install Ansible and retry"
fi

cd $(dirname $0)/ansible
ansible-playbook -i hosts site.yml
