#!/bin/sh
#
# Deploy SAW Security to an environment
#

error() {
    echo "Error: $1"
    echo "Hint: $2"
    exit 1
}

if ! command -v ansible-playbook > /dev/null; then
    message="Ansible required but not found; please install and retry"
    command="yum install epel-release && yum install ansible"
    hint="Install Ansible using \"$command\""
    error "$message" "$hint"
fi

cd $(dirname $0)/ansible
ansible-playbook -i hosts site.yml
