spring:
  application:
    name: saw-batch-ingestion-service
  output:
    ansi:
      enabled: never
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sip_bis
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
    open-in-view: false

logging:
  level:
    com.synchronoss.saw: INFO
    org.springframework: INFO
    org.hibernate.type : INFO

server:
  address: localhost
  port: 9642
  servlet:
    context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
management:
  endpoint:
    health:
      show-details: always
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
sip:
  service:
    index: 0
    max.attempts : 3
    retry.delay: 5000
bis:
  transfer-batch-size: 10
  modified-retries: 3
  default-data-drop-location: /Users/spau0004/Desktop/workbench
  scheduler-url: http://localhost:9601
  recheck-file-modified: false
