spring:
  application:
    name: saw-batch-ingestion-service
  output:
    ansi:
      enabled: never
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sip_batch_ingestion
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
    open-in-view: false
  
logging:
  level:
    com.synchronoss.saw: INFO
    org.springframework: INFO
    org.hibernate.type : INFO
    
server:
  address: localhost
  port: 9642
  servlet:
    context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
management:
  endpoint:
    health:
      show-details: always
sip:
  service:
    index: 0    
    

    