info:
  component: Synchronoss Storage Proxy Service
spring:
  application:
    name: saw-storage-proxy-service
logging:
  level:
    com.synchronoss.saw: info
server:
  address: localhost
  port: 9800
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
schema:
   file: /Users/spau0004/code/SIP/saw-services/saw-proxy-service/src/main/resources/schema/proxy-schema.json
elastic-search:
           cluster-name: elasticsearch
           transport-hosts: es-rd601.ana.dev.vaste.sncrcorp.net,es-rd602.ana.dev.vaste.sncrcorp.net
           transport-ports: 9200,9200
           sslEnabled: false
           keyStorePath: /codebase/sip/server.keystore
           storePassword: es123
elastic-xpack :
          cluster-active: false
          cluster-username: elastic
          cluster-password: xuw3dUraHapret
metastore:
    base:  hdfs:///main
    binary-store-path:  /services/metadata/analysis_results
    migration: analysisMigration


connector : http

metadata:
  service:
    host: ${connector}://localhost:9501
    execution-migration-flag: true
    transporthost: ${connector}://localhost:9200/analysis

sip:
  ssl:
    enable: false
