info:
  component: Synchronoss Storage Proxy Service
spring:
  application:
    name: saw-storage-proxy-service
logging:
  level:
    com.synchronoss.saw: trace
server:
  address: localhost
  port: 9800
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000
schema:
   file: /Users/spau0004/code/SIP/saw-services/saw-proxy-service/src/main/resources/schema/proxy-schema.json
elastic-search:
           cluster-name: elasticsearch
           transport-hosts: es-rd611.eng-sip.dev01.us-west.sncrcloud.net,es-rd612.eng-sip.dev01.us-west.sncrcloud.net,es-rd613.eng-sip.dev01.us-west.sncrcloud.net
           transport-ports: 9200,9200,9200
           sslEnabled: false
           keyStorePath: /codebase/sip/server.keystore
           storePassword: es123
elastic-xpack :
          cluster-active: false
          cluster-username: elastic
          cluster-password: xuw3dUraHapret
metastore:
    base:  hdfs:///var/sip
    binary-store-path:  /services/metadata/analysis_results
    migration: analysisMigration
    ttl-for-onetime: 1800
    analysis: analysisMetadata
    execution-result-limit: 5

execution:
  preview-rows-limit: 10000
  publish-rows-limit: 100000

executor:
  streamPath: /var/sip/services/transport/executor
  wait-time: 120
  preview-output-location: /var/sip/services/transport/executor/output
  publish-schedule-output-location: /var/sip/services/transport/executor

connector : http

metadata:
  service:
    host: ${connector}://localhost:9501
    execution-migration-flag: false
    transporthost: ${connector}://localhost:9200/analysis

sip:
  ssl:
    enable: false
