#'Date Converter Function
#'
#'Date Converter function which is used to convert String date column with
#'given format to Date or Datetime field with format as either yyyy-MM-dd
#'or yyyy-MM-dd HH:mm:ss
#'@param df DataFrame
#'@param measure_vars Input string column which is to be converted to date
#'@param input_format Input format of String column. Allowed formats are
#' MM/dd/yyyy HH:mm:ss, MM/dd/yyyy, yyyy/MM/dd HH:mm:ss, yyyy/MM/dd,
#' dd/MM/yyyy HH:mm:ss, dd/MM/yyyy. The forward slash symbol can be interchanged
#' with hifen.
#'@param output_type Output Data type required. Should be either date or datetime.
#' Default is datetime.
#'@param time_zone Timezone to be considered in Date conversions. Default is UTC
#'@param output_suffix Suffix to be added to the new column generated by the function
#'
#'@return returns DataFrame with converted Date column added with name as
#' {INPUT_COLUMN_NAME}_CONV & format as either yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
#'
#'@export
#'
#'
#'@examples
#'
#'library(dplyr)
#'library(lubridate)
#'
#'date_func_df <- data.frame(STRING_COL = c("2017-01-01 10:15:15", "2017-09-23 14:26:59", "2017-11-15 05:05:05", "2018-05-11 08:15:18", "2018-03-27 23:59:59"), stringsAsFactors = FALSE)
#'
#'converter(date_func_df, "STRING_COL", "yyyy-MM-dd HH:mm:ss", "datetime")

converter <-
  function(df,
           measure_vars,
           input_format,
           output_type,
           time_zone,
           output_suffix) {
    UseMethod("converter")
  }


#' @rdname converter
#' @export
converter.data.frame <- function(df,
                                 measure_vars,
                                 input_format,
                                 output_type = "datetime",
                                 time_zone = "UTC",
                                 output_suffix = "CONV") {
  checkmate::assert_subset(measure_vars, colnames(df), empty.ok = TRUE)

  checkmate::assert_choice(output_type,
                           c("date",
                             "datetime"))

  # Derive Output colum name by adding a configured suffix

  output_col_name <- paste(measure_vars, output_suffix, sep = "_")

  # Get a list of columns to be extracted so that all intermediate columns are removed
  # from final result

  select_vars <- c(colnames(df), output_col_name)

  if(length(measure_vars) == 1) {
    f1_col_name <- "F1"
    f2_col_name <- "F2"
  } else {
    f1_col_name <- paste(measure_vars, "F1", sep = "_")
    f2_col_name <- paste(f1_col_name, "F2", sep = "_")
  }

  # Derive the Input & Output formats required for R data frames in the
  # format required for the lubridate functions

  chk_input_format <- gsub("[^A-z0-9_ ]", "", input_format)
  inp_for_chk <- ""

  inp_for_chk <-
    case_when(
      chk_input_format == "MMddyyyy HHmmss" ~ "mdy_hms",
      chk_input_format == "MMddyyyy" ~ "mdy",
      chk_input_format == "MMddyy" ~ "mdy",
      chk_input_format == "yyyyMMdd HHmmss" ~ "ymd_hms",
      chk_input_format == "yyyyMMdd" ~ "ymd",
      chk_input_format == "ddMMyyyy HHmmss" ~ "dmy_hms",
      chk_input_format == "ddMMyyyy" ~ "dmy"
    )

  dt_chk_fun <- match.fun(inp_for_chk)

  # Update the DF with the output column which will have formatted
  # date value with collapsed period

  if (output_type == "datetime") {
    df <- df %>%
      dplyr::mutate_at(.vars = measure_vars, .funs = funs(F1 = dt_chk_fun)
      ) %>%
      dplyr::rename_(., .dots = setNames(f1_col_name, output_col_name))
  } else {
    df <- df %>%
      dplyr::mutate_at(.vars = measure_vars, .funs = funs(F1 = dt_chk_fun)
      ) %>%
      dplyr::mutate_at(.vars = f1_col_name, .funs = funs(F2 = as.Date)
      ) %>%
      dplyr::rename_(., .dots = setNames(f2_col_name, output_col_name))
  }

  df
}




#' @rdname converter
#' @export
converter.tbl_spark <- function(df,
                                measure_vars,
                                input_format,
                                output_type = "datetime",
                                time_zone = "UTC",
                                output_suffix = "CONV") {
  checkmate::assert_subset(measure_vars, colnames(df), empty.ok = TRUE)

  checkmate::assert_choice(
    input_format,
    c(
      "MM/dd/yyyy HH:mm:ss",
      "MM/dd/yyyy",
      "MM-dd-yyyy HH:mm:ss",
      "MM-dd-yyyy",
      "MM/dd/yy HH:mm:ss",
      "MM/dd/yy",
      "MM-dd-yy HH:mm:ss",
      "MM-dd-yy",
      "yyyy-MM-dd HH:mm:ss",
      "yyyy-MM-dd",
      "yyyy/MM/dd HH:mm:ss",
      "yyyy/MM/dd",
      "dd-MM-yyyy HH:mm:ss",
      "dd-MM-yyyy",
      "dd/MM/yyyy HH:mm:ss",
      "dd/MM/yyyy"
    )
  )

  checkmate::assert_choice(output_type,
                           c("date",
                             "datetime"))

  # Derive Output colum name by adding a configured suffix

  output_col_name <- paste(measure_vars, output_suffix, sep = "_")

  # Get a list of columns to be extracted so that all intermediate columns are removed
  # from final result

  select_vars <- c(colnames(df), output_col_name)

  if(length(measure_vars) == 1) {
    f1_col_name <- "F1"
    f2_col_name <- "F2"
    f3_col_name <- "F3"
  } else {
    f1_col_name <- paste(measure_vars, "F1", sep = "_")
    f2_col_name <- paste(f1_col_name, "F2", sep = "_")
    f3_col_name <- paste(f2_col_name, "F3", sep = "_")
  }

  # Important Note. More testing is required to check if Time zones might be
  # an issue here due to the usage of epoch time for date formatting.

  if (output_type == "datetime") {
    df <- df %>%
      dplyr::mutate_at(.vars = measure_vars, .funs = funs(F1 =
                                                            unix_timestamp, .args = list(input_format))
      ) %>%
      dplyr::mutate_at(.vars = f1_col_name, .funs = funs(F2 = from_unixtime, .args = list("yyyy-MM-dd HH:mm:ss"))
      ) %>%
      dplyr::mutate_at(.vars = f2_col_name, .funs = funs(F3 = to_utc_timestamp, .args = list(time_zone))
      ) %>%
      dplyr::rename_(., .dots = setNames(f3_col_name, output_col_name)) %>%
      select(., select_vars)
  } else {
    df <- df %>%
      dplyr::mutate_at(.vars = measure_vars, .funs = funs(F1 =
                                                            unix_timestamp, .args = list(input_format))
      ) %>%
      dplyr::mutate_at(.vars = f1_col_name, .funs = funs(F2 = from_unixtime, .args = list("yyyy-MM-dd HH:mm:ss"))
      ) %>%
      dplyr::mutate_at(.vars = f2_col_name, .funs = funs(F3 = to_date)
      ) %>%
      dplyr::rename_(., .dots = setNames(f3_col_name, output_col_name)) %>%
      select(., select_vars)
  }

  df
}
