#'Date Converter Function
#'
#'Date Converter function which is used to convert String date column with
#'given format to Date or Datetime field with format as either yyyy-MM-dd
#'or yyyy-MM-dd HH:mm:ss
#'@param df DataFrame
#'@param measure_vars Input string column which is to be converted to date
#'@param input_format Input format of String column. Allowed formats are
#' MM/dd/yyyy HH:mm:ss, MM/dd/yyyy, yyyy/MM/dd HH:mm:ss, yyyy/MM/dd,
#' dd/MM/yyyy HH:mm:ss, dd/MM/yyyy. The forward slash symbol can be interchanged
#' with hifen.
#'@param output_type Output Data type required. Should be either date or datetime.
#' Default is datetime.
#'@param time_zone Timezone to be considered in Date conversions. Default is UTC
#'@param output_suffix Suffix to be added to the new column generated by the function
#'
#'@return returns DataFrame with converted Date column added with name as
#' {INPUT_COLUMN_NAME}_CONV & format as either yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
#'
#'@export
#'
#'
#'@examples
#'
#'library(dplyr)
#'library(lubridate)
#'
#'date_func_df <-
#' data.frame(STRING_COL = as.POSIXlt(
#'  c(
#'    "2017-01-01 10:15:15",
#'    "2017-09-23 14:26:59",
#'    "2017-11-15 05:05:05",
#'    "2018-05-11 08:15:18",
#'    "2018-03-27 23:59:59"
#'  )
#'), stringsAsFactors = FALSE)
#'
#'converter(date_func_df, "STRING_COL", "yyyy-MM-dd HH:mm:ss", "datetime")
#'
converter <-
  function(df,
           measure_vars,
           input_format,
           output_type,
           time_zone,
           output_suffix) {
    UseMethod("converter")
  }


#' @rdname converter
#' @export
converter.data.frame <- function(df,
                                     measure_vars,
                                     input_format,
                                     output_type = "datetime",
                                     time_zone = "UTC",
                                     output_suffix = "CONV") {
  checkmate::assert_subset(measure_vars, colnames(df), empty.ok = TRUE)

  checkmate::assert_choice(output_type,
                           c("date",
                             "datetime"))

  # Derive Output colum name by adding a configured suffix

  output_col_name <- paste(measure_vars, output_suffix, sep = "_")

  # Get a list of columns to be extracted so that all intermediate columns are removed
  # from final result

  select_vars <- c(colnames(df), output_col_name)

  # Derive the Input & Output formats required for R data frames in the
  # format required for the lubridate functions

  chk_input_format <- gsub("[^A-z0-9_ ]", "", input_format)
  inp_for_chk <- ""

  inp_for_chk <-
    case_when(
      chk_input_format == "MMddyyyy HHmmss" ~ "mdy_hms",
      chk_input_format == "MMddyyyy" ~ "mdy",
      chk_input_format == "MMddyy" ~ "mdy",
      chk_input_format == "yyyyMMdd HHmmss" ~ "ymd_hms",
      chk_input_format == "yyyyMMdd" ~ "ymd",
      chk_input_format == "ddMMyyyy HHmmss" ~ "dmy_hms",
      chk_input_format == "ddMMyyyy" ~ "dmy"
    )

  # Update the DF with the output column which will have formatted
  # date value with collapsed period

  if (output_type == "datetime") {
    df <- df %>%
      dplyr::rename(., DT_CHK_1 = !!measure_vars) %>%
      mutate(., !!output_col_name := do.call(inp_for_chk, list(DT_CHK_1))) %>%
      dplyr::rename(., !!measure_vars := DT_CHK_1)
  } else {
    df <- df %>%
      dplyr::rename(., DT_CHK_1 = !!measure_vars) %>%
      mutate(., !!output_col_name := as.Date(do.call(inp_for_chk, list(DT_CHK_1)))) %>%
      dplyr::rename(., !!measure_vars := DT_CHK_1)
  }

  df
}




#' @rdname converter
#' @export
converter.tbl_spark <- function(df,
                                    measure_vars,
                                    input_format,
                                    output_type = "datetime",
                                    time_zone = "UTC",
                                    output_suffix = "CONV") {
  checkmate::assert_subset(measure_vars, colnames(df), empty.ok = TRUE)

  checkmate::assert_choice(
    input_format,
    c(
      "MM/dd/yyyy HH:mm:ss",
      "MM/dd/yyyy",
      "MM-dd-yyyy HH:mm:ss",
      "MM-dd-yyyy",
      "MM/dd/yy HH:mm:ss",
      "MM/dd/yy",
      "MM-dd-yy HH:mm:ss",
      "MM-dd-yy",
      "yyyy-MM-dd HH:mm:ss",
      "yyyy-MM-dd",
      "yyyy/MM/dd HH:mm:ss",
      "yyyy/MM/dd",
      "dd-MM-yyyy HH:mm:ss",
      "dd-MM-yyyy",
      "dd/MM/yyyy HH:mm:ss",
      "dd/MM/yyyy"
    )
  )

  checkmate::assert_choice(output_type,
                           c("date",
                             "datetime"))

  # Derive Output colum name by adding a configured suffix

  output_col_name <- paste(measure_vars, output_suffix, sep = "_")

  # Get a list of columns to be extracted so that all intermediate columns are removed
  # from final result

  select_vars <- c(colnames(df), output_col_name)

  # Important Note. More testing is required to check if Time zones might be
  # an issue here due to the usage of epoch time for date formatting.

  if (output_type == "datetime") {
    df <- df %>%
      rename(., DT_CHK_1 = !!measure_vars) %>%
      mutate(., DER_TIME_1 = from_unixtime(
        unix_timestamp(DT_CHK_1, !!input_format),
        "yyyy-MM-dd HH:mm:ss"
      )) %>%
      mutate(.,!!output_col_name := to_utc_timestamp(DER_TIME_1,!!time_zone)) %>%
      dplyr::rename(., !!measure_vars := DT_CHK_1) %>%
      select(., select_vars)
  } else {
    df <- df %>%
      rename(., DT_CHK_1 = !!measure_vars) %>%
      mutate(., DER_TIME_1 = from_unixtime(
        unix_timestamp(DT_CHK_1, !!input_format),
        "yyyy-MM-dd HH:mm:ss"
      )) %>%
      mutate(., !!output_col_name := to_date(DER_TIME_1)) %>%
      dplyr::rename(., !!measure_vars := DT_CHK_1) %>%
      select(., select_vars)
  }

  df
}
